import {
  THE_DOCTOR_JPG_PROJECTS,
  THE_DOCTOR_JPG_CATEGORIES,
  THE_DOCTOR_JPG_CATEGORY_MAP,
} from './projects-thedoctorjpg.js';

/** @dglogan42's stupid GitHub portfolio — meme fuel */
export const DGLOGAN42_PROJECTS = [
  {
    id: 'lytchgate',
    owner: 'dglogan42',
    name: 'lytchgate',
    repo: 'lytchgate',
    url: 'https://github.com/dglogan42/lytchgate',
    emoji: '🕯️',
    tagline:
      'WITHERMERE — original Victorian survival horror. Mira Alden, Fallowmere House, the Pale Bloom. Pre-rendered rooms, tank controls, eight-slot case, phonograph needles, crest puzzles, two endings. PC browser. Original IP; not affiliated with Capcom / Resident Evil.',
    memeTop: 'SHIPPED A VICTORIAN SURVIVAL HORROR WITH TANK CONTROLS',
    memeBottom: 'the phonograph needs a needle and the latch already fell',
    bg: 'pandemic',
  },
  {
    id: 'spanlight',
    owner: 'dglogan42',
    name: 'Spanlight',
    repo: 'Spanlight',
    url: 'https://github.com/dglogan42/Spanlight',
    emoji: '🌉',
    tagline:
      'Spanlight — original browser lane-siege. Aurel vs Nadir across three living brass spans. Last-hit Glimmers, spend Shards at the Hearth, tear down the Spire. Four Bound. Not Dota, League, or any licensed MOBA.',
    memeTop: 'SHIPPED A LANE SIEGE WHERE THE SPANS ARE ALIVE',
    memeBottom: 'the spire shrugged until i remembered the beacons',
    bg: 'ai',
  },
  {
    id: 'continental-line',
    owner: 'dglogan42',
    name: 'ContinentalLine',
    repo: 'ContinentalLine',
    url: 'https://github.com/dglogan42/ContinentalLine',
    emoji: '🎖️',
    tagline:
      'Continental Line — original American War of Independence real-time tactics. No camps: line, column, square, loose. Volleys, morale, fatigue, woods and redoubts. Lexington to Guilford. PC browser + Gradle WebView APK. Inspired by formation RTS; not affiliated with Veterans: Napoleonic Wars / Tactical Boar.',
    memeTop: 'SHIPPED A FORMATION RTS WHERE THE LINE IS THE UNIT',
    memeBottom: 'militia fired twice then the grenadiers walked through them',
    bg: 'ai',
  },
  {
    id: 'mossglow-island',
    owner: 'dglogan42',
    name: 'MossGlow-Island',
    repo: 'MossGlow-Island',
    url: 'https://github.com/dglogan42/MossGlow-Island',
    emoji: '🍄',
    tagline:
      'Mossglow Isle — original cozy island adventure for Android sideload + PC browser. Farm, fish, mine, cook, hatch Mossglows, clear the Ancient Hollow. Gradle WebView APK, no stamina. Inspired by the farm/explore/companion loop; not affiliated with Luma Island / Feel Free Games.',
    memeTop: 'SHIPPED ANOTHER COZY ISLAND APK WITH LANTERN SPIRITS',
    memeBottom: 'the hollow gate is three stones and the gradle daemon still costs 2 minutes',
    bg: 'ai',
  },
  {
    id: 'holotcg',
    owner: 'dglogan42',
    name: 'HoloTCG',
    repo: 'HoloTCG',
    url: 'https://github.com/dglogan42/HoloTCG',
    emoji: '🎴',
    tagline:
      'HoloTCG / LUMINA — unofficial hololive OCG fan client. Official EN names and public stats, original proxy art, no COVER scans. Browser CPU + LAN rooms, Gradle WebView Android APK. Not affiliated with COVER / hololive / Bushiroad.',
    memeTop: 'SHIPPED AN UNOFFICIAL HOLOLIVE TCG WITH PROXY ART',
    memeBottom: 'sora vs choco on localhost and the apk still says lumina',
    bg: 'ai',
  },
  {
    id: 'bark-derby',
    owner: 'dglogan42',
    name: 'Bark-Derby',
    repo: 'Bark-Derby',
    url: 'https://github.com/dglogan42/Bark-Derby',
    emoji: '🐕',
    tagline:
      'Bark Derby — dog-racing training-sim: scout, train 12 turns, championship race, then karaoke night and date night with five house idols. React + Express + signed Android 8+ APK. Original.',
    memeTop: 'SHIPPED A DOG DERBY APK WITH KARAOKE DATE NIGHT',
    memeBottom: 'vela won the race then asked for moonlight terrace on kibble coins',
    bg: 'ai',
  },
  {
    id: 'portaloo-sim',
    owner: 'dglogan42',
    name: 'Portaloo-Sim',
    repo: 'Portaloo-Sim',
    url: 'https://github.com/dglogan42/Portaloo-Sim',
    emoji: '🚽',
    tagline:
      'The Loo Yard — offline portable toilet hire tycoon. Buy cabins, crew the wash bay, hire to festivals, markets, civil sites and farm weddings. PC browser + WebView Android APK. Original.',
    memeTop: 'SHIPPED A PORTALOO HIRE TYCOON APK',
    memeBottom: 'the festival tagged every cabin and the enzyme still costs $140',
    bg: 'ai',
  },
  {
    id: 'vanguard-command',
    owner: 'dglogan42',
    name: 'Vanguard-Command',
    repo: 'Vanguard-Command',
    url: 'https://github.com/dglogan42/Vanguard-Command',
    emoji: '🛡️',
    tagline:
      'VANGUARD COMMAND — offline squad tactics APK. Four operations (Sector 7 → Core Vault), cards each round, on-device leaderboard. WebView Android 8+. Original; not Nintendo / Marvel / MICA.',
    memeTop: 'SHIPPED A FOUR-OP TACTICS APK WITH NO SERVER',
    memeBottom: '3 energy 3 cards and the leaderboard is localStorage',
    bg: 'ai',
  },
  {
    id: 'franxx-command',
    owner: 'dglogan42',
    name: 'Franxx-Command',
    repo: 'Franxx-Command',
    url: 'https://github.com/dglogan42/Franxx-Command',
    emoji: '🌸',
    tagline:
      'FRANXX COMMAND — unofficial mecha gacha APK. 8-hunt campaign, 3-unit squad, dupe upgrades, pair sync bonus, Plant commissary. Offline WebView Android 8+. Fan project; not Darling in the Franxx / Xenoblade.',
    memeTop: 'SHIPPED AN 8-HUNT MECHA GACHA APK',
    memeBottom: 'ssr is 5% but the mothership still one-shots my dignity',
    bg: 'ai',
  },
  {
    id: 'mossling-meadows',
    owner: 'dglogan42',
    name: 'Mossling-Meadows',
    repo: 'Mossling-Meadows',
    url: 'https://github.com/dglogan42/Mossling-Meadows',
    emoji: '🌿',
    tagline:
      'Mossling — offline cozy valley life-sim for Android sideload + PC browser. Tend Mossvale: gather dew and peat, craft gifts, plant dewleaf, restore a workshop and shrine, befriend ten original moss-folk. WebView APK. Original; not Pokémon Pokopia / Nintendo.',
    memeTop: 'SHIPPED A COZY MOSS VALLEY LIFE-SIM',
    memeBottom: 'the moss-folk ran away because i did not hold still',
    bg: 'ai',
  },
  {
    id: 'atsnz-expo',
    owner: 'dglogan42',
    name: 'ATSNZExpo',
    repo: 'ATSNZExpo',
    url: 'https://github.com/dglogan42/ATSNZExpo',
    emoji: '♿',
    tagline:
      'ATSNZ Access — unofficial Expo web companion for the ATSNZ Disability Expo 2026 at Due Drop Events Centre, Manukau. High contrast, Easy Read, Gate 3 parking, Have a Go, Help now. Not official ATSNZ.',
    memeTop: 'SHIPPED AN ACCESSIBLE EXPO COMPANION',
    memeBottom: 'the seminar programme is still "TBA" but the contrast is yellow on black',
    bg: 'ai',
  },
  {
    id: 'the-silk-roads',
    owner: 'dglogan42',
    name: 'The-Silk-Roads',
    repo: 'The-Silk-Roads',
    url: 'https://github.com/dglogan42/The-Silk-Roads',
    emoji: '🐪',
    tagline:
      'The Silk Roads — 3D globe of 18 land and monsoon corridors, 72 cities, caravan fly-through from Luoyang to Constantinople. Browser Cesium + Google Earth KML. Schematic history, not GPS camel tracks.',
    memeTop: 'MAPPED THE SILK ROAD IN 3D',
    memeBottom: 'still lost between Dunhuang and Kashgar',
    bg: 'ai',
  },
  {
    id: 'sundry',
    owner: 'dglogan42',
    name: 'Sundry',
    repo: 'Sundry',
    url: 'https://github.com/dglogan42/Sundry',
    emoji: '📋',
    tagline:
      'Sundry — rate anything. Pens, incense, Lindt, a bus route. 1–10 plus SS→D boards, lists, share links. Letterboxd / Goodreads energy. Static web, localStorage.',
    memeTop: 'BUILT LETTERBOXD FOR BALLPOINT PENS',
    memeBottom: 'this incense is SS. this bus route is D',
    bg: 'ai',
  },
  {
    id: 'herd',
    owner: 'dglogan42',
    name: 'Herd',
    repo: 'Herd',
    url: 'https://github.com/dglogan42/Herd',
    emoji: '🦬',
    tagline:
      'Herd — anonymous campus feed for Android. Hot/New, votes, comments, peek other herds, GPS radius. Original; not Yik Yak. Room demo, six campuses.',
    memeTop: 'SHIPPED AN ANONYMOUS CAMPUS FEED',
    memeBottom: 'peeked UCLA then immediately went back to my own herd',
    bg: 'ai',
  },
  {
    id: 'ink',
    owner: 'dglogan42',
    name: 'Ink',
    repo: 'Ink',
    url: 'https://github.com/dglogan42/Ink',
    emoji: '💬',
    tagline:
      'Ink — Instagram messenger without Instagram. Notes, requests folder, group threads, hearts. No feed, no Reels, no Meta. Android Room demo.',
    memeTop: 'BUILT INSTAGRAM DMS WITHOUT INSTAGRAM',
    memeBottom: 'the notes are 60 characters. the dignity is still in requests',
    bg: 'ai',
  },
  {
    id: 'local-marketplace',
    owner: 'dglogan42',
    name: 'local-marketplace',
    repo: 'local-marketplace',
    url: 'https://github.com/dglogan42/local-marketplace',
    emoji: '🛋️',
    tagline:
      'Stoop — local classifieds without Facebook. Two-week listings, typed first messages, no "is this available?". Android Room demo, one city (SF). Not Marketplace / Meta.',
    memeTop: 'SHIPPED MARKETPLACE WITHOUT THE META',
    memeBottom: 'is this available? no. type a real sentence',
    bg: 'ai',
  },
  {
    id: 'vitalstatistix',
    owner: 'dglogan42',
    name: 'Vitalstatistix',
    repo: 'Vitalstatistix',
    url: 'https://github.com/dglogan42/Vitalstatistix',
    emoji: '🩺',
    tagline:
      'Vitalstatistix — local-first Health.app for Android. Kotlin + Jetpack Compose on Health Connect: one timeline, two-second logging, honest widgets. Symptoms, brushing, meds, labs. No company server, no INTERNET. Apache 2.0. Not a medical device.',
    memeTop: 'SHIPPED APPLE HEALTH FOR ANDROID BECAUSE I WAS MAD',
    memeBottom: 'minSdk 34. the timeline is empty. samsung still has the watch',
    bg: 'pandemic',
  },
  {
    id: 'rubble-app',
    owner: 'dglogan42',
    name: 'Rubble-App',
    repo: 'Rubble-App',
    url: 'https://github.com/dglogan42/Rubble-App',
    emoji: '🧱',
    tagline:
      'Out of the Rubble — Gracecity Church 8-week Nehemiah personal journey. Native Android (Java + JDK + Android SDK): weekly practices, lined journal, great-work sentence, bundled booklet PDF, sermon links. Offline. Apache 2.0.',
    memeTop: 'SHIPPED AN 8-WEEK NEHEMIAH JOURNEY APP FOR CHURCH',
    memeBottom: 'the wall is still rubble. the journal is on-device. god is not in the cloud',
    bg: 'ai',
  },
  {
    id: 'frisco-founders-club',
    owner: 'dglogan42',
    name: 'Frisco-Founders-Club',
    repo: 'Frisco-Founders-Club',
    url: 'https://github.com/dglogan42/Frisco-Founders-Club',
    emoji: '🌁',
    tagline:
      'Fogline — San Francisco club for founders, operators, and investors who meet through sport and wellness. Android (Kotlin + Compose): this week’s events, RSVP, member directory, 1:1 chat. MIT. Not Golden Born Society.',
    memeTop: 'SHIPPED A FOUNDER CLUB FOR PEOPLE WHO ACTUALLY RUN',
    memeBottom: 'linkedin but the event is 6:30am embarcadero and nobody ghosted',
    bg: 'ai',
  },
  {
    id: 'nineties-fighter',
    owner: 'dglogan42',
    name: 'Nineties-Fighter',
    repo: 'Nineties-Fighter',
    url: 'https://github.com/dglogan42/Nineties-Fighter',
    emoji: '🥊',
    tagline:
      'HYPER RUSH — 3-on-3 90s arcade tag fighter (Icons vs Outlaws). Assists, launchers, Variable Combination, Level 3 hypers. Web + signed Android 8+ APK. Original roster; not Marvel vs Capcom.',
    memeTop: 'SHIPPED A 90S ARCADE TAG FIGHTER',
    memeBottom: 'quarter-circled into a variable combination then forgot to block',
    bg: 'ai',
  },
  {
    id: 'starroot-isle',
    owner: 'dglogan42',
    name: 'Starroot-Isle',
    repo: 'Starroot-Isle',
    url: 'https://github.com/dglogan42/Starroot-Isle',
    emoji: '🌱',
    tagline:
      'Starroot Isle — original cozy island adventure for Android. Farm, mine, fish, craft, Heartseed story, puffkin companions, local + online visit co-op. Procedural 56×56 island. MIT original IP; not Stardew / Animal Crossing.',
    memeTop: 'SHIPPED A COZY ISLAND ADVENTURE',
    memeBottom: 'watered the crops. the Heartseed is still judging me',
    bg: 'ai',
  },
  {
    id: 'apks',
    owner: 'dglogan42',
    name: 'APKs',
    repo: 'APKs',
    url: 'https://github.com/dglogan42/APKs',
    emoji: '📦',
    tagline:
      'Sideloadable Android APKs for dglogan42 games — one repo, many unknown-sources installs. Companion dump for the portfolio fighters, sims, and JRPGs.',
    memeTop: 'DUMPED EVERY GAME APK IN ONE REPO',
    memeBottom: 'unknown sources: on. dignity: still sideloading',
    bg: 'ai',
  },
  {
    id: 'cursed-circuit',
    owner: 'dglogan42',
    name: 'Cursed-Circuit',
    repo: 'Cursed-Circuit',
    url: 'https://github.com/dglogan42/Cursed-Circuit',
    emoji: '🧿',
    tagline:
      'CURSED CIRCUIT — original jujutsu-academy JRPG homage. Octopath BP/Break, Chained Echoes Overdrive, King\'s Fingers, Domain Expansion. Web 320×240 + signed Android 8+ APK. Not official JJK.',
    memeTop: 'SHIPPED A JUJUTSU ACADEMY JRPG IN 320×240',
    memeBottom: 'swallowed two King\'s Fingers and called it a job system',
    bg: 'ai',
  },
  {
    id: 'haiyaku-beach-volleyball',
    owner: 'dglogan42',
    name: 'Haiyaku-Beach-Volleyball',
    repo: 'Haiyaku-Beach-Volleyball',
    url: 'https://github.com/dglogan42/Haiyaku-Beach-Volleyball',
    emoji: '🏐',
    tagline:
      'HAIYAKU! Beach Volleyball — week-long beach training camp. 2v2 sand volleyball, tiki bar, infinity pool, suikawari / fireworks / shaved ice / swimsuit boutique. Web + signed Android 8+ APK. Original roster; not Haikyū!! or DOA Xtreme.',
    memeTop: 'SHIPPED A BEACH EPISODE WITH ACTUAL 2V2 VOLLEYBALL',
    memeBottom: 'HAIYAKU!! quick attack then immediately lose to shaved ice',
    bg: 'ai',
  },
  {
    id: 'sakura-mart',
    owner: 'dglogan42',
    name: 'Sakura-Mart',
    repo: 'Sakura-Mart',
    url: 'https://github.com/dglogan42/Sakura-Mart',
    emoji: '🛒',
    tagline:
      'ちびマート / CHIBI MART — chibi Japanese supermarket sim in Game Boy Advance pixel graphics + chiptunes. Web (240×160) and signed Android 8+ APK. Stock shelves, scan neighbors, 7-day week. Offline landscape pad.',
    memeTop: 'SHIPPED A GBA SUPERMARKET SIM IN 240×160',
    memeBottom: 'customers ragequit while the onigiri is still in the back room',
    bg: 'ai',
  },
  {
    id: 'bread',
    owner: 'dglogan42',
    name: 'Bread',
    repo: 'Bread',
    url: 'https://github.com/dglogan42/Bread',
    emoji: '🍞',
    tagline:
      'Bread — cozy bakery shop sim for Android & iOS (Expo / React Native). Order supplies, bake 10 recipes, serve impatient customers, pay rent, unlock progression. Day cycle, energy, autosave. EAS preview APK ready.',
    memeTop: 'SHIPPED A BAKERY SIM WITH REAL RENT ENERGY',
    memeBottom: 'customers ragequit while the croissants are still proving',
    bg: 'ai',
  },
  {
    id: 'supa-saver',
    owner: 'dglogan42',
    name: 'Supa-Saver',
    repo: 'Supa-Saver',
    url: 'https://github.com/dglogan42/Supa-Saver',
    emoji: '🛒',
    tagline:
      "Supa Saver — NZ supermarket price spy (Expo + Express). Compare Woolworths, New World, PAK'nSAVE & FreshChoice. Barcode scan, unit prices, region GPS, shopping list with cheapest-store / multi-store split plan. Live API + offline catalogue fallback.",
    memeTop: 'BUILT A 4-STORE NZ GROCERY PRICE SPY',
    memeBottom: "split the basket across three shops to save $2.40. worth it?",
    bg: 'ai',
  },
  {
    id: 'toyfinder',
    owner: 'dglogan42',
    name: 'ToyFinder',
    repo: 'ToyFinder',
    url: 'https://github.com/dglogan42/ToyFinder',
    emoji: '🧸',
    tagline:
      'ToyFinder — preorder upcoming toys before they sell out. Expo mobile + Vite web share one NZD catalog. Search/filter by brand & category, limited-edition badges, cart, checkout form, on-device preorder history. Sample catalog; no live payments.',
    memeTop: 'SHIPPED A TOY PREORDER STOREFRONT',
    memeBottom: 'limited edition sold out while I was still in checkout',
    bg: 'ai',
  },
  {
    id: 'hardware-help',
    owner: 'dglogan42',
    name: 'Hardware-Help',
    repo: 'Hardware-Help',
    url: 'https://github.com/dglogan42/Hardware-Help',
    emoji: '🔧',
    tagline:
      'Hardware Help / Aisle Finder — AR aisle locate + 15% price match for Bunnings & Mitre 10. Capacitor web→Android/iOS. Search, floor maps, dual-chain aisle/bay/shelf, shopping list, optional AI photo ID. Offline catalogue bundled.',
    memeTop: 'SHIPPED AR AISLE FINDER FOR TWO HARDWARE CHAINS',
    memeBottom: 'price matched 15% and still got lost in timber',
    bg: 'ai',
  },
  {
    id: 'space-factory',
    owner: 'dglogan42',
    name: 'Space-Factory',
    repo: 'Space-Factory',
    url: 'https://github.com/dglogan42/Space-Factory',
    emoji: '🚀',
    tagline:
      'Space Factory — Android orbital factory sim. Mine asteroids, smelt metal, fabricate chips, launch starships. 48×32 grid, Ore→Metal→Chips→Ships chain, solar power network, 15-ship victory fleet. Touch pan/zoom, auto-save. Original; not affiliated with Factorio / Wube.',
    memeTop: 'SHIPPED AN ORBITAL FACTORY ON ANDROID',
    memeBottom: 'ran out of chips. the solar panels are judging me',
    bg: 'ai',
  },
  {
    id: 'pebble-cove',
    owner: 'dglogan42',
    name: 'Pebble-Cove',
    repo: 'Pebble-Cove',
    url: 'https://github.com/dglogan42/Pebble-Cove',
    emoji: '🏝️',
    tagline:
      'Pebble Cove — original offline village / collectible life-sim for Android (Kotlin + Compose). Island map, day/night energy, bugs/fish/shells/forage, NPCs, shop, cottage décor, collection book. Local DataStore only. Free, no ads; not affiliated with Nintendo / Chucklefish / ConcernedApe.',
    memeTop: 'SHIPPED AN OFFLINE ISLAND LIFE-SIM',
    memeBottom: 'spent all energy on shells. nana wren is disappointed',
    bg: 'ai',
  },
  {
    id: 'fair-dinkum-trivia',
    owner: 'dglogan42',
    name: 'FairDinkum-Trivia',
    repo: 'FairDinkum-Trivia',
    url: 'https://github.com/dglogan42/FairDinkum-Trivia',
    emoji: '🇦🇺',
    tagline:
      'Fair Dinkum Trivia — original offline Australian general-knowledge quiz for Android (Kotlin + Jetpack Compose). 15-step prize ladder, safe levels, 50:50 / Ask the Crowd / Skip lifelines, 130+ AU questions, local high scores only. Free, no ads, not affiliated with any TV quiz show.',
    memeTop: 'SHIPPED OFFLINE AU TRIVIA FOR ANDROID',
    memeBottom: 'walked away at $32k. still failed the emu question',
    bg: 'ai',
  },
  {
    id: 'tryline-sevens',
    owner: 'dglogan42',
    name: 'TryLine-Sevens',
    repo: 'TryLine-Sevens',
    url: 'https://github.com/dglogan42/TryLine-Sevens',
    emoji: '🏉',
    tagline:
      "Tryline Sevens '98 — HK / Wellington Sevens–style 7-a-side cup rugby for Android sideload + PC browser. Short halves, pass/kick/sprint, QF→SF→Cup Final. Original fan-style arcade energy; not Jonah Lomu Rugby; not affiliated with World Rugby / Codemasters / unions.",
    memeTop: "SHIPPED SEVENS '98 ARCADE RUGBY",
    memeBottom: 'dropped it in the cup final. still not jonah lomu',
    bg: 'ai',
  },
  {
    id: 'flare',
    owner: 'dglogan42',
    name: 'Flare',
    repo: 'Flare',
    url: 'https://github.com/dglogan42/Flare',
    emoji: '🔥',
    tagline:
      'Flare Android (Offline) — packaging helpers for the free/libre Flare ARPG engine + Empyrean Campaign. Official engine APK, mods zip, install checklist; optional source build. Not a reimplementation; credits Flare / flarerpg.org (GPL).',
    memeTop: 'PACKAGED FLARE FOR OFFLINE ANDROID',
    memeBottom: 'forgot the mods zip. engine said path not found',
    bg: 'ai',
  },
  {
    id: 'shardfall',
    owner: 'dglogan42',
    name: 'Shardfall',
    repo: 'Shardfall',
    url: 'https://github.com/dglogan42/Shardfall',
    emoji: '⚔️',
    tagline:
      'Shardfall — offline Diablo-style action RPG for Android sideload + PC browser. Procedural floors, loot, skills, boss every 5 floors. Spellblade / Warden / Arcanist. Original code; not affiliated with Blizzard / Level-5 / Netmarble.',
    memeTop: 'SHIPPED A DIABLO-STYLE OFFLINE ARPG',
    memeBottom: 'died to the floor 5 boss with full inventory',
    bg: 'ai',
  },
  {
    id: 'metro-dash',
    owner: 'dglogan42',
    name: 'MetroDash',
    repo: 'MetroDash',
    url: 'https://github.com/dglogan42/MetroDash',
    emoji: '🚇',
    tagline:
      'Metro Dash PC — original Windows endless runner. 3 lanes, jump, slide, coins, magnet/boost/shield power-ups, Xbox pad support. Offline, no Steam. Not Subway Surfers; not affiliated with Kiloo / SYBO.',
    memeTop: 'SHIPPED A METRO ENDLESS RUNNER FOR PC',
    memeBottom: 'hit the train. high score was 12 coins',
    bg: 'ai',
  },
  {
    id: 'hololive-dreams',
    owner: 'dglogan42',
    name: 'HoloLive-Dreams',
    repo: 'HoloLive-Dreams',
    url: 'https://github.com/dglogan42/HoloLive-Dreams',
    emoji: '🎮',
    tagline:
      'Dream Park PC — offline Windows fan demo (not Steam, not the official game). Park hub + 4-lane rhythm + Hoppin\' Rope minigame + quests, Xbox 360/One/Series support, Web Audio synth. Unofficial; not affiliated with COVER / hololive / QualiArts.',
    memeTop: 'SHIPPED A HOLOLIVE DREAMS PC FAN DEMO',
    memeBottom: 'no steam. no servers. just D F J K and emotional damage',
    bg: 'ai',
  },
  {
    id: 'mythicats',
    owner: 'dglogan42',
    name: 'mythicats',
    repo: 'mythicats',
    url: 'https://github.com/dglogan42/mythicats',
    emoji: '🐱',
    tagline:
      'Pokémon GO–style open-world AR hunt for mythical cats. Web (Three.js + GPS) + Android (ARCore Geospatial, SceneView/Filament glTF, multiplayer spawns). Catch with Catnip, Tuna, or Milk. MIT monorepo. Not affiliated with Pokémon/Niantic.',
    memeTop: "SHIPPED A POKÉMON GO CLONE BUT IT'S CATS",
    memeBottom: 'threw milk at a void kitten. still in demo mode',
    bg: 'ai',
  },
  {
    id: 'convention-expo',
    owner: 'dglogan42',
    name: 'Convention-Expo',
    repo: 'Convention-Expo',
    url: 'https://github.com/dglogan42/Convention-Expo',
    emoji: '🎫',
    tagline:
      'Con/expo volunteer toolkit — Grok event-volunteer skill, Overload NZ packs, applications, ICS, guests/events cheat sheets, floor landmarks. Personal data redacted. Crew first, chaos second.',
    memeTop: 'SHIPPED A FULL CONVENTION VOLUNTEER OPS KIT',
    memeBottom: 'my break plan has more acts than the main stage',
    bg: 'ai',
  },
  {
    id: 'voice-agent',
    owner: 'dglogan42',
    name: 'Voice-Agent',
    repo: 'Voice-Agent',
    url: 'https://github.com/dglogan42/Voice-Agent',
    emoji: '🎙️',
    tagline:
      'Carina — ADHD-friendly xAI Realtime scheduling voice agent. Calendar clash checks, PII scrub, 1737 crisis handoff. No medical advice, just appointments.',
    memeTop: 'BUILT A VOICE AGENT NAMED CARINA',
    memeBottom: 'she books the GP then refuses my double-book (adhd said send it)',
    bg: 'ai',
  },
  {
    id: 'witch-dating',
    owner: 'dglogan42',
    name: 'Witch-Dating',
    repo: 'Witch-Dating',
    url: 'https://github.com/dglogan42/Witch-Dating',
    emoji: '🪄',
    tagline:
      "Thorn Scarhart dating & social kit — 17th-c witch spell-yeeted into modern apps (An Ancient Witch's Guide to Modern Dating vibes). Tinder bio, IG/Bluesky packs, Don't Stop Believin' Radio, thirst stills, 6s reels, and a Grok skill that posts to all her socials. Marriage-minded. Algorithm-cursed.",
    memeTop: 'BUILT A FULL DATING KIT FOR A TIME-TRAVEL WITCH',
    memeBottom: 'the hex failed. the content calendar did not',
    bg: 'ai',
  },
  {
    id: 'ubuntu-live-desktop',
    owner: 'dglogan42',
    name: 'Ubuntu-Live-Desktop',
    repo: 'Ubuntu-Live-Desktop',
    url: 'https://github.com/dglogan42/Ubuntu-Live-Desktop',
    emoji: '🖥️',
    tagline:
      'StudioWall — live wallpaper for Ubuntu Studio / KDE Plasma (Wayland + X11). Loop cinematic MP4/WebM on the desktop with a dark control GUI, system tray, CLI, multi-monitor surfaces, and login autostart. Wallspace vibes, zero subscription, pure PyQt6 chaos.',
    memeTop: 'SHIPPED LIVE WALLPAPERS FOR UBUNTU STUDIO',
    memeBottom: 'my desktop is now a 6-second aurora and 12% CPU',
    bg: 'ai',
  },
  {
    id: 'dropzone-royale',
    owner: 'dglogan42',
    name: 'Dropzone-Royale',
    repo: 'Dropzone-Royale',
    url: 'https://github.com/dglogan42/Dropzone-Royale',
    emoji: '🪂',
    tagline:
      'Dropzone Royale — Linux-native offline battle royale (HTML5 Canvas). Plane drop, loot, shrinking blue zone, ~48 AI rivals, last standing. Genre-inspired by PUBG-style loops (Steam 578080); MIT original code — not a Krafton port, not affiliated with PUBG/Valve. ./scripts/run-linux.sh and dignity optional.',
    memeTop: 'SHIPPED A LINUX BATTLE ROYALE',
    memeBottom: 'winner winner… local python http.server',
    bg: 'ai',
  },
  {
    id: 'blade-arena',
    owner: 'dglogan42',
    name: 'Blade-Arena',
    repo: 'Blade-Arena',
    url: 'https://github.com/dglogan42/Blade-Arena',
    emoji: '⚔',
    tagline:
      'Blade Arena — offline Android sideload tactical sword fighter (Blade Symphony–inspired). 1v1 / 2v2 / FFA / Control Points, five fighters, five swords, four stances, timed parries. WebView + HTML5 Canvas, MIT code, fan-work notice. Prove you are the world\'s greatest swordsman (on a Chinese tablet with unknown sources on).',
    memeTop: 'SHIPPED A BLADE SYMPHONY CLONE FOR TABLETS',
    memeBottom: 'parried in WebView. still Mixed reviews on Steam (the real one)',
    bg: 'ai',
  },
  {
    id: 'ubuntu-studio-tablet',
    owner: 'dglogan42',
    name: 'Ubuntu-Studio-Tablet',
    repo: 'Ubuntu-Studio-Tablet',
    url: 'https://github.com/dglogan42/Ubuntu-Studio-Tablet',
    emoji: '🖥️',
    tagline:
      'Tablet-first Ubuntu Studio 26.04 layer — Plasma fullscreen app launchers, Xiaoxin laptop dual-boot (BitLocker/Fast Startup/shrink), ARM/Plasma Mobile path, Waydroid helpers. No kernel, no bootloader unlock, just vibes and kwinrulesrc.',
    memeTop: 'SHIPPED A TABLET OS FOR STUDIO APPS',
    memeBottom: 'my Xiaoxin Pad is still on Android (wrong ISA)',
    bg: 'ai',
  },
  {
    id: 'steam-mods',
    owner: 'dglogan42',
    name: 'steam-mods',
    repo: 'steam-mods',
    url: 'https://github.com/dglogan42/steam-mods',
    emoji: '🎮',
    tagline:
      'Umamusume Linux Tools & Mods — GE-Proton/external Steam library setup, Linux-patched UMML, headless patch-mods.py, play/apply scripts. MIT for helpers only; Cygames assets not included. Proton prefix diaries welcome.',
    memeTop: 'SHIPPED STEAM MOD TOOLS FOR LINUX',
    memeBottom: 'GE-Proton installed. dignity still downloading',
    bg: 'ai',
  },
  {
    id: 'alchemised',
    owner: 'dglogan42',
    name: 'alchemised',
    repo: 'alchemised',
    url: 'https://github.com/dglogan42/alchemised',
    emoji: '⚗',
    tagline:
      'Alchemised: Resonance — pixel-art RPG Android APK (sideload) inspired by SenLinYu\'s Alchemised. Memory shards, manor crawl, alchemy bench, Alchemist / Vivimancer / Necromancer classes. Unofficial fan tribute, MIT code, T-rated.',
    memeTop: 'SIDEOADED A DARK FANTASY PIXEL RPG',
    memeBottom: 'my Resonance is sealed but the APK installs (unknown sources on)',
    bg: 'ai',
  },
  {
    id: 'flying-fox',
    owner: 'dglogan42',
    name: 'Flying Fox',
    repo: 'flying-fox',
    url: 'https://github.com/dglogan42/flying-fox',
    emoji: '🦊',
    tagline:
      'Flying Fox — cozy hex tile-laying deckbuilder (Hexfell/Dorfromantik vibes) + Firefox extension. Forest/meadow/water/rock edges, hand of 3, quests, localStorage best. Flap was v1; the canopy is the product now.',
    memeTop: 'SHIPPED A TILE-LAYING DECKBUILDER',
    memeBottom: 'still calling it Flying Fox like it flaps (it places hexes)',
    bg: 'berry',
  },
  {
    id: 'visual-diary',
    owner: 'dglogan42',
    name: 'Visual-Diary',
    repo: 'Visual-Diary',
    url: 'https://github.com/dglogan42/Visual-Diary',
    emoji: '📔',
    tagline:
      'Spine · Open Studio — marketing kit for a visual diary app: waitlist pages (en/es/fr/en-AU), Starter Packs, #OpenStudioFriday, brand tokens. Campaign before product (classic).',
    memeTop: 'SHIPPED THE OPEN STUDIO CAMPAIGN',
    memeBottom: 'the app is still a waitlist (story unfinished)',
    bg: 'liveLaugh',
  },
  {
    id: 'puzzler',
    owner: 'dglogan42',
    name: 'Puzzler',
    repo: 'Puzzler',
    url: 'https://github.com/dglogan42/Puzzler',
    emoji: '🧩',
    tagline:
      'Puzzle Sorter — find puzzles, AR piece assist (colour/edges/grid), frames/glue/mats, clubs & table nights. React 19 + Zustand PWA, NZ seed catalogue. Edge pieces first, life later.',
    memeTop: 'BUILT AN AR PUZZLE SORTER',
    memeBottom: 'still missing three pieces and the will to glue it',
    bg: 'minion',
  },
  {
    id: 'marketing-kit',
    owner: 'dglogan42',
    name: 'Marketing-Kit',
    repo: 'Marketing-Kit',
    url: 'https://github.com/dglogan42/Marketing-Kit',
    emoji: '📣',
    tagline:
      'Full-stack marketing kit studio — live-event promos, Bluesky-first campaigns, AI generate-from-source (SpaceXAI/xAI). React + Express + file catalog. BABYMONSTER Auckland + Own Your Sky seeds.',
    memeTop: 'BUILT A MARKETING KIT FACTORY',
    memeBottom: 'my own launch plan is still a sticky note',
    bg: 'ai',
  },
  {
    id: 'drone-hire',
    owner: 'dglogan42',
    name: 'Drone-Hire',
    repo: 'Drone-Hire',
    url: 'https://github.com/dglogan42/Drone-Hire',
    emoji: '🛸',
    tagline:
      'Hire drones + optional pilots for photo, cinema, survey, thermal, FPV, ag. Fleet filters, live quotes, list-your-own. React 19 + Zustand PWA, NZ seed fleet. CAA vibes, localStorage only.',
    memeTop: 'SHIPPED A DRONE HIRE APP',
    memeBottom: 'my only flight is the demo booking (Part 101 pending)',
    bg: 'berry',
  },
  {
    id: 'trails-companion',
    owner: 'dglogan42',
    name: 'Trails-Companion',
    repo: 'Trails-Companion',
    url: 'https://github.com/dglogan42/Trails-Companion',
    emoji: '🥾',
    tagline:
      'Local hiking group social app — discover walks, join crews, RSVP meetups, trail catalog. React + Vite + Zustand, localStorage demo. Boots on, trail legs optional.',
    memeTop: 'SHIPPED A HIKING MEETUP APP',
    memeBottom: 'still “might go” on every RSVP (my couch is a trail)',
    bg: 'berry',
  },
  {
    id: 'paleo-pal',
    owner: 'dglogan42',
    name: 'Paleo-Pal',
    repo: 'Paleo-Pal',
    url: 'https://github.com/dglogan42/Paleo-Pal',
    emoji: '🥩',
    tagline:
      'Paleo calorie & macro tracker — calorie ring, meal sections, ~40 staples, 7-day history. React 19 + Vite. localStorage only. Caveman diet, modern UI guilt.',
    memeTop: 'TRACKED EVERY GRAM OF BISON',
    memeBottom: 'then ate a pastry and closed the tab',
    bg: 'minion',
  },
  {
    id: 'sew-and-sew',
    owner: 'dglogan42',
    name: 'Sew-And-Sew',
    repo: 'Sew-And-Sew',
    url: 'https://github.com/dglogan42/Sew-And-Sew',
    emoji: '🧵',
    tagline:
      'Craft community for sewing, crochet, knitting, embroidery, quilting, mending — patterns, clubs, stitch-night RSVPs. React + Zustand PWA demo. Seamstress energy, unfinished WIP pile.',
    memeTop: 'JOINED A SEWING CIRCLE APP',
    memeBottom: 'my only finished project is the README',
    bg: 'liveLaugh',
  },
  {
    id: 'birdy-bro',
    owner: 'dglogan42',
    name: 'birdy-bro',
    repo: 'birdy-bro',
    url: 'https://github.com/dglogan42/birdy-bro',
    emoji: '🦜',
    tagline:
      'Field guide, life list & spot log for amateur ornithologists — 50+ species, GPS, photos, hotspots, optional SpaceXAI ID. Mobile-first PWA. Birds > people.',
    memeTop: 'LOGGED A RARE SIGHTING',
    memeBottom: 'it was a pigeon. I still put it on the life list',
    bg: 'berry',
  },
  {
    id: 'biker-meet',
    owner: 'dglogan42',
    name: 'Biker-Meet',
    repo: 'Biker-Meet',
    url: 'https://github.com/dglogan42/Biker-Meet',
    emoji: '🏍️',
    tagline:
      'Group rides for motorcyclists and cycle clubs — discover rides, join chapters, RSVP, plan runs, garage profile. React + Vite PWA, NZ-flavoured demo data.',
    memeTop: 'BUILT A GROUP RIDE APP',
    memeBottom: 'my bike is still in the shop (and so is my courage)',
    bg: 'ai',
  },
  {
    id: 'pickle-padel',
    owner: 'dglogan42',
    name: 'Pickle-Padel',
    repo: 'Pickle-Padel',
    url: 'https://github.com/dglogan42/Pickle-Padel',
    emoji: '🥒',
    tagline:
      'Pickleball + padel club app — tournaments, solo join, partner queue, leaderboards, club meets. React + Zustand localStorage. Two sports, one midlife crisis.',
    memeTop: 'HOSTED A PICKLEBALL OPEN',
    memeBottom: 'still can’t return serve (or emails)',
    bg: 'minion',
  },
  {
    id: 'kart-lap',
    owner: 'dglogan42',
    name: 'Kart-Lap',
    repo: 'Kart-Lap',
    url: 'https://github.com/dglogan42/Kart-Lap',
    emoji: '🏎️',
    tagline:
      'Lapline — pit-lane lap timer & scoreboard for go-kart challenges. F1-style lights-out start, splits, P1 gaps. Single static HTML + localStorage. No build, pure red mist.',
    memeTop: 'LIGHTS OUT AND AWAY WE GO',
    memeBottom: 'best lap was the practice one I forgot to save',
    bg: 'ai',
  },
  {
    id: 'the-good-herbs',
    owner: 'dglogan42',
    name: 'The-Good-Herbs',
    repo: 'The-good-herbs',
    url: 'https://github.com/dglogan42/The-good-herbs',
    emoji: '🌱',
    tagline:
      'Local garden club finder, seed & bulb swap board, and a hemisphere-aware planting calendar. React + Vite + Express + SQLite, so a herb club gets a full stack app.',
    memeTop: 'SHIPPED A GARDEN CLUB FINDER + SEED SWAP APP',
    memeBottom: 'my actual garden: one dead basil plant',
    bg: 'berry',
  },
  {
    id: 'camera-trader',
    owner: 'dglogan42',
    name: 'Camera-Trader',
    repo: 'Camera-Trader',
    url: 'https://github.com/dglogan42/Camera-Trader',
    emoji: '📷',
    tagline:
      'Auckland camera trade-in hub — grade gear, store credit vs cash (Stripe Connect sim), inventory, shutter depreciation, stolen-serial mock. SNAP is dead; SeriSafe is homework; 105 is real.',
    memeTop: 'BUILT A CAMERA TRADE APP',
    memeBottom: 'snap.org.nz decommissioned (serials still haunt me)',
    bg: 'ai',
  },
  {
    id: 'vinyl-addict',
    owner: 'dglogan42',
    name: 'Vinyl-Addict',
    repo: 'Vinyl-Addict',
    url: 'https://github.com/dglogan42/Vinyl-Addict',
    emoji: '💿',
    tagline:
      'Vinyl Addict × Real Groovy PWA — scan covers, collection, mock trade-in grade, cash vs store credit (+10%). React + Vite + Express. iOS/Android/desktop installable.',
    memeTop: 'SCANNED MY ENTIRE COLLECTION',
    memeBottom: 'real groovy still wants the actual records in a bag',
    bg: 'berry',
  },
  {
    id: 'uma-companion',
    owner: 'dglogan42',
    name: 'Uma-Companion',
    repo: 'Uma-Companion',
    url: 'https://github.com/dglogan42/Uma-Companion',
    emoji: '💜',
    tagline:
      'Personal PWA companion — offline chat, mood check-ins, private notes. React + Vite + service worker. Data stays on-device. Installable on phone and desktop.',
    memeTop: 'SHIPPED A COMPANION APP',
    memeBottom: 'she only exists in localStorage (still better than my DMs)',
    bg: 'liveLaugh',
  },
  {
    id: 'fetchly',
    owner: 'dglogan42',
    name: 'Fetchly',
    repo: 'Fetchly',
    url: 'https://github.com/dglogan42/Fetchly',
    emoji: '🛴',
    tagline:
      'Student neighborhood delivery — email-only signup, walk/bike/scooter/skateboard couriers, no driver’s license. React + Express + SQLite. Snacks before school, chaos after.',
    memeTop: 'BUILT A TEEN DELIVERY APP',
    memeBottom: 'no license required (neither is a business plan)',
    bg: 'minion',
  },
  {
    id: 'manga-mate',
    owner: 'dglogan42',
    name: 'Manga-Mate',
    repo: 'Manga-Mate',
    url: 'https://github.com/dglogan42/Manga-Mate',
    emoji: '📚',
    tagline:
      'Manga series tracker by genre + chapter progress. PWA + Electron + Capacitor Android. localStorage only. Offline shell. TBR pile grows anyway.',
    memeTop: 'TRACKED 200 SERIES',
    memeBottom: 'still “catching up” on chapter 3',
    bg: 'berry',
  },
  {
    id: 'brick-bud',
    owner: 'dglogan42',
    name: 'Brick-Bud',
    repo: 'Brick-Bud',
    url: 'https://github.com/dglogan42/Brick-Bud',
    emoji: '🧱',
    tagline:
      'LEGO® Collectible Minifig tracker — Expo + React Native, 28 CMF series, owned/wishlist, spend vs value, per-series completion. Local AsyncStorage only. Pure blind-bag pain.',
    memeTop: 'BUILT A MINIFIG TRACKER',
    memeBottom: 'still bought the same figure twice (blind bag tax)',
    bg: 'minion',
  },
  {
    id: 'warband',
    owner: 'dglogan42',
    name: 'WarBand',
    repo: 'WarBand',
    url: 'https://github.com/dglogan42/WarBand',
    emoji: '⚔️',
    tagline:
      'Teams/Slack-style hub for tabletop groups — channels, calendar ICS sync, Socket.IO chat, Jitsi video, JWT + SQLite, optional Teams manifest + Slack Bolt bot.',
    memeTop: 'BUILT A TABLETOP TEAMS APP',
    memeBottom: 'session zero is still in the group chat (nobody rsvpd)',
    bg: 'liveLaugh',
  },
  {
    id: 'dispensa',
    owner: 'dglogan42',
    name: 'Dispensa',
    repo: 'Dispensa',
    url: 'https://github.com/dglogan42/Dispensa',
    emoji: '💊',
    tagline:
      'Pharmacist AR support tool — eRx queue, camera AR overlays, accuracy checks, drug interaction engine, QR/PDF intake, SpaceXAI clinical narratives (demo CDS only).',
    memeTop: 'BUILT PHARMACY AR SOFTWARE',
    memeBottom: 'the interactions are real; the license is demo-only',
    bg: 'ai',
  },
  {
    id: 'cosplay-meetup-manager',
    owner: 'dglogan42',
    name: 'Cosplay-Meetup-Manager',
    repo: 'Cosplay-Meetup-Manager',
    url: 'https://github.com/dglogan42/Cosplay-Meetup-Manager',
    emoji: '🎭',
    tagline:
      'Cosplay meetup event planner — checklist, attendees, schedule, localStorage, and share to LINE / KakaoTalk / WeChat / WhatsApp / Discord. No backend. Pure con-prep chaos.',
    memeTop: 'BUILT A COSPLAY MEETUP APP',
    memeBottom: 'still sewing the costume the night before',
    bg: 'berry',
  },
  {
    id: 'church-date',
    owner: 'dglogan42',
    name: 'Church-Date',
    repo: 'Church-Date',
    url: 'https://github.com/dglogan42/Church-Date',
    emoji: '✝️',
    tagline:
      'Kindred — faith-based dating. Next.js + Prisma + NextAuth, 18+ gate, real photo onboarding, mutual match, chat, verse of the day by tradition.',
    memeTop: 'BUILT A CHURCH DATING APP',
    memeBottom: 'mutual match before you DMs (amen)',
    bg: 'liveLaugh',
  },
  {
    id: 'milf-mate',
    owner: 'dglogan42',
    name: 'MILF-Mate',
    repo: 'MILF-Mate',
    url: 'https://github.com/dglogan42/MILF-Mate',
    emoji: '🔥',
    tagline:
      'Location-based discover app — swipe, filters, matches, Haversine distance. Demo seed personas only; real product needs real opt-in users. React + Express + SQLite PWA.',
    memeTop: 'SHIPPED A GEO HOOKUP APP',
    memeBottom: 'the seed profiles are fictional (the cringe is real)',
    bg: 'berry',
  },
  {
    id: 'palagi-life',
    owner: 'dglogan42',
    name: 'palagi-life',
    repo: 'palagi-life',
    url: 'https://github.com/dglogan42/palagi-life',
    emoji: '💒',
    tagline:
      'Self-deprecating blog + simulated live stream (palagi_live) + TikTok kit. Sione’s Wedding energy offline; chat flirts online; he thanks “stay after? xx” for the roadmap.',
    memeTop: 'SHE TIPPED 500 BITS',
    memeBottom: 'i thanked her for supporting the channel roadmap',
    bg: 'berry',
  },
  {
    id: 'delphitools-mobile',
    owner: 'dglogan42',
    name: 'delphitools-mobile',
    repo: 'delphitools-mobile',
    url: 'https://github.com/dglogan42/delphitools-mobile',
    emoji: '🧰',
    tagline:
      'Mobile-first privacy-first browser tools + an unhinged AI Prompt Pack (Agent Team, FMCG ads, Blender MCP, VRM, DAW…). Vite + React. No login. Just vibes.',
    memeTop: 'BUILT ANOTHER TOOLKIT',
    memeBottom: 'now it has 20 prompt packs and a vrm exporter (still no users)',
    bg: 'ai',
  },
  {
    id: 'user-ex-int',
    owner: 'dglogan42',
    name: 'User-Ex-Int',
    repo: 'User-Ex-Int',
    url: 'https://github.com/dglogan42/User-Ex-Int',
    emoji: '🕸️',
    tagline:
      'User Experience Intelligence via Graph Engineering — multi-agent loops with shared memory (generate → critique → revise → graph that survives sessions).',
    memeTop: 'AGENTS NEED SHARED MEMORY',
    memeBottom: 'built a graph so the swarm stops gaslighting itself',
    bg: 'ai',
  },
  {
    id: 'bubble-tea-news',
    owner: 'dglogan42',
    name: 'bubble-tea-news',
    repo: 'bubble-tea-news',
    url: 'https://github.com/dglogan42/bubble-tea-news',
    emoji: '🧋',
    tagline:
      "Fictional Auckland bubble-tea freesheet — weekly satirical issues, print PDFs, and a whole coffee-news energy empire. Claude-Skills writes it; this repo ships it.",
    memeTop: 'LAUNCHED A NEWSPAPER',
    memeBottom: 'for bubble tea (print-ready pdfs btw)',
    bg: 'berry',
  },
  {
    id: 'sapiolink',
    owner: 'dglogan42',
    name: 'SapioLink',
    repo: 'SapioLink',
    url: 'https://github.com/dglogan42/SapioLink',
    emoji: '💌',
    tagline: 'Dating app landing page — write a letter before you see a face. Vite + React, sincere by accident.',
    memeTop: 'MADE A DATING APP',
    memeBottom: 'you fall for the paragraph before the face (still single btw)',
    bg: 'berry',
  },
  {
    id: 'fable-offline',
    owner: 'dglogan42',
    name: 'Fable-Offline',
    repo: 'Fable-Offline',
    url: 'https://github.com/dglogan42/Fable-Offline',
    emoji: '🧠',
    tagline:
      'Offline Fable 5 agent — Ollama chat, loop engineering, self-improving skills. Maker ≠ grader. No cloud tax.',
    memeTop: 'FABLE 5 OFFLINE MODE',
    memeBottom: 'no api key. no rate limit. just pure local rigour (and a 7b model)',
    bg: 'ai',
  },
  {
    id: 'coursex-agents',
    owner: 'dglogan42',
    name: 'CourseX-Agents',
    repo: 'CourseX-Agents',
    url: 'https://github.com/dglogan42/CourseX-Agents',
    emoji: '🤖',
    tagline: 'Agent swarm for CourseX — multi-agent course chaos in Python.',
    memeTop: 'COURSEX AGENTS ASSEMBLE',
    memeBottom: 'one agent to syllabus them all',
    bg: 'ai',
  },
  {
    id: 'coursex',
    owner: 'dglogan42',
    name: 'CourseX',
    repo: 'CourseX',
    url: 'https://github.com/dglogan42/CourseX',
    emoji: '📚',
    tagline: 'CourseX platform core — courses, content, and educational pipeline energy.',
    memeTop: 'COURSEX JUST DROPPED',
    memeBottom: 'another learning platform nobody asked for (i asked)',
    bg: 'adhd',
  },
  {
    id: 'v8-supercars',
    owner: 'dglogan42',
    name: 'V8-Supercars',
    repo: 'V8-Supercars',
    url: 'https://github.com/dglogan42/V8-Supercars',
    emoji: '🏎️',
    tagline: 'iOS + Android PWA — DAZZA bogan Supercars commentary, Clip Studio, Openrestream rebroadcast.',
    memeTop: 'LIGHTS OUT AND AWAY WE GO',
    memeBottom: 'dazza said yeah nah send it mate',
    bg: 'fifa',
  },
  {
    id: 'card-collector',
    owner: 'dglogan42',
    name: 'Card-Collector',
    repo: 'Card-Collector',
    url: 'https://github.com/dglogan42/Card-Collector',
    emoji: '🃏',
    tagline: 'iOS + Android TCG con companion — scan, grade, trade, and pay with Stripe/PayPal/Apple Pay/Google Pay at the booth.',
    memeTop: 'SCANNED A CHARIZARD AT THE CON',
    memeBottom: 'grade says 10. wallet says apple pay. wife says leave',
    bg: 'berry',
  },
  {
    id: 'mission-not-ready',
    owner: 'dglogan42',
    name: 'Mission-Not-Ready',
    repo: 'Mission-Not-Ready',
    url: 'https://github.com/dglogan42/Mission-Not-Ready',
    emoji: '🏢',
    tagline: 'Satire meme lab roasting missionreadyhq.com — on-site with no site, no Wi‑Fi, phantom classrooms. Multi-format export + share packs.',
    memeTop: 'SIGNED UP FOR ON-SITE',
    memeBottom: 'arrives to an empty nest (no wifi)',
    bg: 'ai',
  },
  {
    id: 'witchfire',
    owner: 'dglogan42',
    name: 'Witchfire',
    repo: 'Witchfire',
    url: 'https://github.com/dglogan42/Witchfire',
    emoji: '🔥',
    tagline: 'Full 3-act Broadway musical + EPUB — Basque witch-hunt of 1609, but make it showtunes.',
    memeTop: 'WITCHFIRE IN LABOURD',
    memeBottom: 'broadway said burn the receipts (1609)',
    bg: 'adhd',
  },
  {
    id: 'abg-finder',
    owner: 'dglogan42',
    name: 'ABG-Finder',
    repo: 'ABG-Finder',
    url: 'https://github.com/dglogan42/ABG-Finder',
    emoji: '💅',
    tagline: 'Swipe ABGs, rate bubble tea sweetness, track the sauce.',
    memeTop: 'ME BUILDING AN ABG DATING APP',
    memeBottom: 'with ramen spiciness ratings fr',
    bg: 'berry',
  },
  {
    id: 'valorant-streamer',
    owner: 'dglogan42',
    name: 'Valorant-Streamer',
    repo: 'Valorant-Streamer',
    url: 'https://github.com/dglogan42/Valorant-Streamer',
    emoji: '▲',
    tagline: 'Twitch ladder, gift subs, Throne wishlists, clip studio.',
    memeTop: 'STREAMLADDER MMR',
    memeBottom: 'clip the ace. post the cringe gif.',
    bg: 'stream',
  },
  {
    id: 'glasgow-2026',
    owner: 'dglogan42',
    name: 'Glasgow-2026',
    repo: 'Glasgow-2026',
    url: 'https://github.com/dglogan42/Glasgow-2026',
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    tagline: 'Morag MacMeme Scots TTS for Commonwealth Games chaos.',
    memeTop: 'MORAG MACMEME SAID',
    memeBottom: 'pure gallus commonwealth energy',
    bg: 'liveLaugh',
  },
  {
    id: 'sports-clip-studio',
    owner: 'dglogan42',
    name: 'sports-clip-studio',
    repo: 'sports-clip-studio',
    url: 'https://github.com/dglogan42/sports-clip-studio',
    emoji: '✂️',
    tagline: 'Trim sports commentary clips. Share to Bluesky & podcasts.',
    memeTop: 'SPORTS CLIP STUDIO',
    memeBottom: 'trim the hype. blast it to mastodon.',
    bg: 'fifa',
  },
  {
    id: 'f1-season',
    owner: 'dglogan42',
    name: 'F1-Season',
    repo: 'F1-Season',
    url: 'https://github.com/dglogan42/F1-Season',
    emoji: '🏎️',
    tagline: '2026 championship dashboard, Monaco timeline, Speed Racer memes.',
    memeTop: 'ROAD TO MONACO',
    memeBottom: 'radiohead lyrics but make it f1',
    bg: 'fifa',
  },
  {
    id: 'le-tour',
    owner: 'dglogan42',
    name: 'le-tour',
    repo: 'le-tour',
    url: 'https://github.com/dglogan42/le-tour',
    emoji: '🚴',
    tagline: 'Tour de France tracker with unreasonable French meme energy.',
    memeTop: 'MAILLot JAUNE ENERGY',
    memeBottom: 'openstreetmap but make it baguette',
    bg: 'liveLaugh',
  },
  {
    id: '12th-man',
    owner: 'dglogan42',
    name: '12th-Man',
    repo: '12th-Man',
    url: 'https://github.com/dglogan42/12th-Man',
    emoji: '🏏',
    tagline: 'Twelfth Man spoof Ashes commentary with Bill Lawry chaos.',
    memeTop: 'BILL LAWRY AT 3AM',
    memeBottom: 'marvellous marvellous ashes tts',
    bg: 'fifa',
  },
  {
    id: 'all-blacks',
    owner: 'dglogan42',
    name: 'All-Blacks-Season',
    repo: 'All-Blacks-Season',
    url: 'https://github.com/dglogan42/All-Blacks-Season',
    emoji: '🏉',
    tagline: 'Bledisloe Cup tracker + sausage roll stadium reviews.',
    memeTop: 'ALL BLACKS SEASON',
    memeBottom: 'election week crowd spotting nz',
    bg: 'pandemic',
  },
  {
    id: 'wimbledon',
    owner: 'dglogan42',
    name: 'Road-To-Wimbledon',
    repo: 'Road-To-Wimbledon',
    url: 'https://github.com/dglogan42/Road-To-Wimbledon',
    emoji: '🎾',
    tagline: 'ASB Classic → Roland Garros → Wimbledon drama meters.',
    memeTop: 'TANTRUM TICKER SAYS',
    memeBottom: 'celebrity spotter at all england',
    bg: 'liveLaugh',
  },
  {
    id: 'wwe',
    owner: 'dglogan42',
    name: 'WWE-Wrestlemania',
    repo: 'WWE-Wrestlemania',
    url: 'https://github.com/dglogan42/WWE-Wrestlemania',
    emoji: '💪',
    tagline: 'Road to WrestleMania hype cards. Roast superstars IWC style.',
    memeTop: 'ROAD TO WRESTLEMANIA',
    memeBottom: 'hype your guy. roast the fed.',
    bg: 'stream',
  },
  {
    id: 'pga-masters',
    owner: 'dglogan42',
    name: 'PGA-Masters',
    repo: 'PGA-Masters',
    url: 'https://github.com/dglogan42/PGA-Masters',
    emoji: '⛳',
    tagline: 'PGA Tour leaderboards, FedEx Cup, Masters Fan Zone.',
    memeTop: 'BIRDIE FEED ACTIVATED',
    memeBottom: 'masters fan zone clip studio',
    bg: 'pandemic',
  },
  {
    id: 'asian-supermarket',
    owner: 'dglogan42',
    name: 'Asian-Supermarket',
    repo: 'Asian-Supermarket',
    url: 'https://github.com/dglogan42/Asian-Supermarket',
    emoji: '🛒',
    tagline: 'Find Asian supermarkets. Voice search. Hungry Panda delivery.',
    memeTop: 'ASIAN SUPERMARKET LOCATOR',
    memeBottom: 'hungry panda integration nobody asked for',
    bg: 'berry',
  },
  {
    id: 'healthpoint',
    owner: 'dglogan42',
    name: 'Healthpoint',
    repo: 'Healthpoint',
    url: 'https://github.com/dglogan42/Healthpoint',
    emoji: '🏥',
    tagline: 'NZ chemists, GPs, physios, ACC/WINZ — maps linked.',
    memeTop: 'HEALTHPOINT FINDER',
    memeBottom: 'find a chemist in aotearoa bestie',
    bg: 'ai',
  },
  {
    id: 'anime-filter',
    owner: 'dglogan42',
    name: 'Instagram-Anime-Effect',
    repo: 'Instagram-Anime-Effect',
    url: 'https://github.com/dglogan42/Instagram-Anime-Effect',
    emoji: '🎨',
    tagline: 'Cel-shaded anime camera filter PWA for Instagram.',
    memeTop: 'ANIME FILTER PWA',
    memeBottom: 'instagram stories but youre ghibli',
    bg: 'adhd',
  },
  {
    id: 'european-pantry',
    owner: 'dglogan42',
    name: 'European-Pantry',
    repo: 'European-Pantry',
    url: 'https://github.com/dglogan42/European-Pantry',
    emoji: '🥐',
    tagline: 'European food shop for NZ — Auckland, Wellington, Christchurch.',
    memeTop: 'CONTINENTAL PANTRY',
    memeBottom: 'european snacks in christchurch',
    bg: 'liveLaugh',
  },
  {
    id: 'ozbiz',
    owner: 'dglogan42',
    name: 'OzBiz-Properties',
    repo: 'OzBiz-Properties',
    url: 'https://github.com/dglogan42/OzBiz-Properties',
    emoji: '🏢',
    tagline: 'Australian commercial real estate — offices, warehouses, retail.',
    memeTop: 'OZBIZ PROPERTIES',
    memeBottom: 'warehouse industrial core australia',
    bg: 'ai',
  },
  {
    id: 'rednote-trader',
    owner: 'dglogan42',
    name: 'Rednote-Trader',
    repo: 'Rednote-Trader',
    url: 'https://github.com/dglogan42/Rednote-Trader',
    emoji: '📕',
    tagline: 'Xiaohongshu-style marketplace with Stripe & PayPal.',
    memeTop: 'REDNOTE TRADING',
    memeBottom: 'little red book but make it stripe',
    bg: 'berry',
  },
  {
    id: 'rednote-streaming',
    owner: 'dglogan42',
    name: 'Rednote-Streaming',
    repo: 'Rednote-Streaming',
    url: 'https://github.com/dglogan42/Rednote-Streaming',
    emoji: '📺',
    tagline: 'RedNote Chrome extension — livestream to X and Bluesky.',
    memeTop: 'REDNOTE EXTENSION',
    memeBottom: 'livestream xiaohongshu to bluesky',
    bg: 'stream',
  },
  {
    id: 'uncensored-ai',
    owner: 'dglogan42',
    name: 'Uncensored-AI',
    repo: 'Uncensored-AI',
    url: 'https://github.com/dglogan42/Uncensored-AI',
    emoji: '🤖',
    tagline: 'Local AI studio — SD, LLMs, Whisper, Kokoro, video gen.',
    memeTop: 'UNCENSORED LOCAL STUDIO',
    memeBottom: 'stable diffusion on my laptop at 3am',
    bg: 'ai',
  },
  {
    id: 'creampie-calculator',
    owner: 'dglogan42',
    name: 'Creampie-Time-Calculator',
    repo: 'Creampie-Time-Calculator',
    url: 'https://github.com/dglogan42/Creampie-Time-Calculator',
    emoji: '🥧',
    tagline: 'Ovulation tracker with whipped-cream pastry alert when it\'s baby time.',
    memeTop: 'CREAMPIE TIME CALCULATOR',
    memeBottom: 'load the whipped cream at ovulation o\'clock',
    bg: 'berry',
  },
  {
    id: 'hogwarts-sherlock',
    owner: 'dglogan42',
    name: 'Hogwarts-Sherlock',
    repo: 'Hogwarts-Sherlock',
    url: 'https://github.com/dglogan42/Hogwarts-Sherlock',
    emoji: '🔍',
    tagline: '33k-word EPUB — Mr Holmes on TikTok meets teenage secret notebook energy.',
    memeTop: 'ELEMENTARY MY DEAR TIKTOKER',
    memeBottom: 'chromatography at baker street secondary fr',
    bg: 'adhd',
  },
  {
    id: 'openstream',
    owner: 'dglogan42',
    name: 'Openstream',
    repo: 'Openstream',
    url: 'https://github.com/dglogan42/Openstream',
    emoji: '📡',
    tagline: 'Free open-source multi-site streamer — one ingest, many platforms via FFmpeg.',
    memeTop: 'STREAM ONCE TO EVERYTHING',
    memeBottom: 'self-hosted restream on a free plan forever',
    bg: 'stream',
  },
  {
    id: 'openrestream',
    owner: 'dglogan42',
    name: 'Openrestream',
    repo: 'Openrestream',
    url: 'https://github.com/dglogan42/Openrestream',
    emoji: '🔀',
    tagline: 'Standalone multistream app + OBS Lua companion — one OBS feed, many platforms.',
    memeTop: 'OPENRESTREAM + OBS',
    memeBottom: 'stream once. fan out forever. self-hosted.',
    bg: 'stream',
  },
  {
    id: 'beastwars-tcg',
    owner: 'dglogan42',
    name: 'Beastwars-TCG',
    repo: 'Beastwars-TCG',
    url: 'https://github.com/dglogan42/Beastwars-TCG',
    emoji: '🤖',
    tagline: 'Beast Wars Transformers TCG PWA — 100+ cards, expansions, battle vs AI.',
    memeTop: 'BEAST WARS TCG LIVE',
    memeBottom: 'energon cost 5. waszinator gets ko\'d again',
    bg: 'fifa',
  },
  {
    id: 'christmas-countdown',
    owner: 'dglogan42',
    name: 'Christmas-Countdown',
    repo: 'Christmas-Countdown',
    url: 'https://github.com/dglogan42/Christmas-Countdown',
    emoji: '🎄',
    tagline: 'Buddy, Grinch & Jack — cozy -ber months, raid party, Feliz Navidad karaoke PWA.',
    memeTop: 'COUNTDOWN TO CHRISTMAS',
    memeBottom: 'jack singing feliz navidad at the halloween raid',
    bg: 'liveLaugh',
  },
  {
    id: 'azogue-netflix',
    owner: 'dglogan42',
    name: 'Azogue-Netflix',
    repo: 'Azogue-Netflix',
    url: 'https://github.com/dglogan42/Azogue-Netflix',
    emoji: '🎬',
    tagline: 'Netflix-adjacent viewing chaos. Queue the doomscroll.',
    memeTop: 'AZOGUE NETFLIX',
    memeBottom: 'are you still watching? of course you are',
    bg: 'stream',
  },
  {
    id: 'slam-poet',
    owner: 'dglogan42',
    name: 'Slam-Poet',
    repo: 'Slam-Poet',
    url: 'https://github.com/dglogan42/Slam-Poet',
    emoji: '🎤',
    tagline: 'Spoken-word / slam poetry tooling for the mic-drop adjacent.',
    memeTop: 'SLAM POET MODE',
    memeBottom: 'finger snaps in the comments only',
    bg: 'adhd',
  },
  {
    id: 'the-fallen-seed',
    owner: 'dglogan42',
    name: 'THE-FALLEN-SEED',
    repo: 'THE-FALLEN-SEED',
    url: 'https://github.com/dglogan42/THE-FALLEN-SEED',
    emoji: '🌱',
    tagline: 'Dark-seed creative project energy. Grow something cursed.',
    memeTop: 'THE FALLEN SEED',
    memeBottom: 'plant trauma. harvest lore.',
    bg: 'pandemic',
  },
  {
    id: 'adhd-ardour',
    owner: 'dglogan42',
    name: 'ADHD-Ardour',
    repo: 'ADHD-Ardour',
    url: 'https://github.com/dglogan42/ADHD-Ardour',
    emoji: '🎛️',
    tagline: 'Ardour DAW + ADHD workflow chaos. Record before the hyperfocus ends.',
    memeTop: 'ADHD ARDOUR SESSION',
    memeBottom: '17 tracks muted. one perfect take. lost the project file.',
    bg: 'adhd',
  },
  {
    id: 'observability-toolkit',
    owner: 'dglogan42',
    name: 'observability-monitoring-toolkit',
    repo: 'observability-monitoring-toolkit',
    url: 'https://github.com/dglogan42/observability-monitoring-toolkit',
    emoji: '📊',
    tagline: 'Monitoring / observability toolkit. Graphs for people who graph their feelings.',
    memeTop: 'OBSERVABILITY TOOLKIT',
    memeBottom: 'my metrics are down bad',
    bg: 'ai',
  },
  {
    id: 'cringe-memes',
    owner: 'dglogan42',
    name: 'cringe-memes-bluesky',
    repo: 'cringe-memes-bluesky',
    url: 'https://github.com/dglogan42/cringe-memes-bluesky',
    emoji: '🦋',
    tagline: 'This app. Bluesky feed → cringe memes. Maximum regret.',
    memeTop: 'CRINGE MEME GENERATOR',
    memeBottom: 'recursively cringe (this repo)',
    bg: 'berry',
  },
  {
    id: 'claude-skills',
    owner: 'dglogan42',
    name: 'Claude-Skills',
    repo: 'Claude-Skills',
    url: 'https://github.com/dglogan42/Claude-Skills',
    emoji: '🧩',
    tagline: 'Custom Claude Code skills — found-footage screenplay method, tabloid gossip voice, whatever chaos comes next.',
    memeTop: 'WROTE A CLAUDE SKILL FOR THAT',
    memeBottom: 'there is now a slash command for the vibes',
    bg: 'ai',
  },
  {
    id: 'unlisted',
    owner: 'dglogan42',
    name: 'UNLISTED',
    repo: 'UNLISTED',
    url: 'https://github.com/dglogan42/UNLISTED',
    emoji: '💾',
    tagline: 'Found-footage horror screenplay — an SD card mailed with no return address, three people go looking, one very bad ARG.',
    memeTop: 'FOUND THE UNLISTED FOLDER',
    memeBottom: 'should NOT have opened it',
    bg: 'pandemic',
  },
  {
    id: 'production-notes',
    owner: 'dglogan42',
    name: 'production-notes',
    repo: 'production-notes',
    url: 'https://github.com/dglogan42/production-notes',
    emoji: '🧘',
    tagline: 'Evening yoga routine that spiralled into a full shoot brief, call sheet, choreography count, and location scout guide.',
    memeTop: 'ASKED FOR A WIND-DOWN ROUTINE',
    memeBottom: 'received an entire production bible',
    bg: 'liveLaugh',
  },
  {
    id: 'ai-friend',
    owner: 'dglogan42',
    name: 'AI-Friend',
    repo: 'AI-Friend',
    url: 'https://github.com/dglogan42/AI-Friend',
    emoji: '🐱',
    tagline: 'Cat-eared VR companion, in pseudocode: BEGIN heard ← Listen(); reply ← Think(heard); Emote(reply.mood); Speak(reply.text) END.',
    memeTop: 'BEGIN COMPANION.EXE',
    memeBottom: 'openai has no billing, kimi is broke, but the cat ears compile',
    bg: 'ai',
  },
];

export const PROJECT_CATEGORIES = [
  { id: 'all', label: 'All Chaos' },
  { id: 'sports', label: '🏆 Sports' },
  { id: 'games', label: '🎮 Games' },
  { id: 'chaos', label: '💀 Chaos Apps' },
  { id: 'commerce', label: '🛒 Commerce' },
  { id: 'writing', label: '✍️ Writing' },
];

export const PROJECT_CATEGORY_MAP = {
  lytchgate: 'games',
  spanlight: 'games',
  'continental-line': 'games',
  'mossglow-island': 'games',
  'holotcg': 'games',
  'bark-derby': 'games',
  'portaloo-sim': 'games',
  'vanguard-command': 'games',
  'franxx-command': 'games',
  'mossling-meadows': 'games',
  'atsnz-expo': 'chaos',
  'the-silk-roads': 'chaos',
  'sundry': 'chaos',
  'herd': 'chaos',
  'ink': 'chaos',
  'local-marketplace': 'commerce',
  'vitalstatistix': 'chaos',
  'rubble-app': 'chaos',
  'frisco-founders-club': 'sports',
  'nineties-fighter': 'games',
  'starroot-isle': 'games',
  'apks': 'games',
  'cursed-circuit': 'games',
  'haiyaku-beach-volleyball': 'sports',
  'sakura-mart': 'games',
  'bread': 'games',
  'supa-saver': 'commerce',
  'toyfinder': 'commerce',
  'hardware-help': 'commerce',
  'space-factory': 'games',
  'pebble-cove': 'games',
  'fair-dinkum-trivia': 'games',
  'tryline-sevens': 'sports',
  'flare': 'games',
  'shardfall': 'games',
  'metro-dash': 'games',
  'hololive-dreams': 'games',
  'convention-expo': 'chaos',
  'voice-agent': 'chaos',
  'witch-dating': 'writing',
  'ubuntu-live-desktop': 'chaos',
  'dropzone-royale': 'games',
  'blade-arena': 'games',
  'ubuntu-studio-tablet': 'chaos',
  'steam-mods': 'games',
  'alchemised': 'games',
  'mythicats': 'games',
  'flying-fox': 'games',
  'visual-diary': 'chaos',
  'puzzler': 'games',
  'marketing-kit': 'chaos',
  'drone-hire': 'commerce',
  'trails-companion': 'chaos',
  'paleo-pal': 'chaos',
  'sew-and-sew': 'chaos',
  'birdy-bro': 'chaos',
  'biker-meet': 'sports',
  'pickle-padel': 'sports',
  'kart-lap': 'sports',
  'the-good-herbs': 'commerce',
  'fable-offline': 'chaos',
  'coursex-agents': 'chaos',
  'coursex': 'chaos',
  'v8-supercars': 'sports',
  'card-collector': 'games',
  'mission-not-ready': 'chaos',
  'abg-finder': 'chaos',
  'valorant-streamer': 'chaos',
  'glasgow-2026': 'sports',
  'sports-clip-studio': 'sports',
  'f1-season': 'sports',
  'le-tour': 'sports',
  '12th-man': 'sports',
  'all-blacks': 'sports',
  'wimbledon': 'sports',
  'wwe': 'sports',
  'pga-masters': 'sports',
  'asian-supermarket': 'commerce',
  'healthpoint': 'chaos',
  'anime-filter': 'chaos',
  'european-pantry': 'commerce',
  'ozbiz': 'commerce',
  'rednote-trader': 'commerce',
  'rednote-streaming': 'chaos',
  'uncensored-ai': 'chaos',
  'creampie-calculator': 'chaos',
  'hogwarts-sherlock': 'writing',
  'witchfire': 'writing',
  'openstream': 'chaos',
  'openrestream': 'chaos',
  'beastwars-tcg': 'games',
  'christmas-countdown': 'chaos',
  'azogue-netflix': 'chaos',
  'slam-poet': 'writing',
  'the-fallen-seed': 'writing',
  'adhd-ardour': 'chaos',
  'observability-toolkit': 'chaos',
  'cringe-memes': 'chaos',
  'unlisted': 'writing',
  'claude-skills': 'chaos',
  'production-notes': 'chaos',
  'sapiolink': 'writing',
  'ai-friend': 'chaos',
  'delphitools-mobile': 'chaos',
  'user-ex-int': 'chaos',
  'bubble-tea-news': 'writing',
  'palagi-life': 'writing',
  'cosplay-meetup-manager': 'chaos',
  'church-date': 'chaos',
  'milf-mate': 'chaos',
  'brick-bud': 'games',
  'warband': 'chaos',
  'dispensa': 'chaos',
  'camera-trader': 'commerce',
  'vinyl-addict': 'commerce',
  'uma-companion': 'chaos',
  'fetchly': 'commerce',
  'manga-mate': 'games',
};

/** @deprecated use DGLOGAN42_PROJECTS */
export const GITHUB_PROJECTS = DGLOGAN42_PROJECTS;

export const GITHUB_ACCOUNTS = [
  {
    id: 'dglogan42',
    username: 'dglogan42',
    label: '@dglogan42',
    url: 'https://github.com/dglogan42',
    projects: DGLOGAN42_PROJECTS,
    categories: PROJECT_CATEGORIES,
    categoryMap: PROJECT_CATEGORY_MAP,
  },
  {
    id: 'thedoctorjpg',
    username: 'Thedoctorjpg',
    label: '@Thedoctorjpg',
    url: 'https://github.com/Thedoctorjpg',
    projects: THE_DOCTOR_JPG_PROJECTS,
    categories: THE_DOCTOR_JPG_CATEGORIES,
    categoryMap: THE_DOCTOR_JPG_CATEGORY_MAP,
  },
];