/** @dglogan42's stupid GitHub portfolio — meme fuel */
export const GITHUB_PROJECTS = [
  {
    id: 'abg-finder',
    name: 'ABG-Finder',
    repo: 'ABG-Finder',
    url: 'https://github.com/dglogan42/ABG-Finder',
    emoji: '💅',
    tagline: 'Swipe ABGs, rate bubble tea sweetness, track the sauce.',
    memeTop: 'ME BUILDING AN ABG DATING APP',
    memeBottom: 'with ramen spiciness ratings fr',
    bg: 'berry',
  },
  {
    id: 'valorant-streamer',
    name: 'Valorant-Streamer',
    repo: 'Valorant-Streamer',
    url: 'https://github.com/dglogan42/Valorant-Streamer',
    emoji: '▲',
    tagline: 'Twitch ladder, gift subs, Throne wishlists, clip studio.',
    memeTop: 'STREAMLADDER MMR',
    memeBottom: 'clip the ace. post the cringe gif.',
    bg: 'stream',
  },
  {
    id: 'glasgow-2026',
    name: 'Glasgow-2026',
    repo: 'Glasgow-2026',
    url: 'https://github.com/dglogan42/Glasgow-2026',
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    tagline: 'Morag MacMeme Scots TTS for Commonwealth Games chaos.',
    memeTop: 'MORAG MACMEME SAID',
    memeBottom: 'pure gallus commonwealth energy',
    bg: 'liveLaugh',
  },
  {
    id: 'sports-clip-studio',
    name: 'sports-clip-studio',
    repo: 'sports-clip-studio',
    url: 'https://github.com/dglogan42/sports-clip-studio',
    emoji: '✂️',
    tagline: 'Trim sports commentary clips. Share to Bluesky & podcasts.',
    memeTop: 'SPORTS CLIP STUDIO',
    memeBottom: 'trim the hype. blast it to mastodon.',
    bg: 'fifa',
  },
  {
    id: 'f1-season',
    name: 'F1-Season',
    repo: 'F1-Season',
    url: 'https://github.com/dglogan42/F1-Season',
    emoji: '🏎️',
    tagline: '2026 championship dashboard, Monaco timeline, Speed Racer memes.',
    memeTop: 'ROAD TO MONACO',
    memeBottom: 'radiohead lyrics but make it f1',
    bg: 'fifa',
  },
  {
    id: 'le-tour',
    name: 'le-tour',
    repo: 'le-tour',
    url: 'https://github.com/dglogan42/le-tour',
    emoji: '🚴',
    tagline: 'Tour de France tracker with unreasonable French meme energy.',
    memeTop: 'MAILLot JAUNE ENERGY',
    memeBottom: 'openstreetmap but make it baguette',
    bg: 'liveLaugh',
  },
  {
    id: '12th-man',
    name: '12th-Man',
    repo: '12th-Man',
    url: 'https://github.com/dglogan42/12th-Man',
    emoji: '🏏',
    tagline: 'Twelfth Man spoof Ashes commentary with Bill Lawry chaos.',
    memeTop: 'BILL LAWRY AT 3AM',
    memeBottom: 'marvellous marvellous ashes tts',
    bg: 'fifa',
  },
  {
    id: 'all-blacks',
    name: 'All-Blacks-Season',
    repo: 'All-Blacks-Season',
    url: 'https://github.com/dglogan42/All-Blacks-Season',
    emoji: '🏉',
    tagline: 'Bledisloe Cup tracker + sausage roll stadium reviews.',
    memeTop: 'ALL BLACKS SEASON',
    memeBottom: 'election week crowd spotting nz',
    bg: 'pandemic',
  },
  {
    id: 'wimbledon',
    name: 'Road-To-Wimbledon',
    repo: 'Road-To-Wimbledon',
    url: 'https://github.com/dglogan42/Road-To-Wimbledon',
    emoji: '🎾',
    tagline: 'ASB Classic → Roland Garros → Wimbledon drama meters.',
    memeTop: 'TANTRUM TICKER SAYS',
    memeBottom: 'celebrity spotter at all england',
    bg: 'liveLaugh',
  },
  {
    id: 'wwe',
    name: 'WWE-Wrestlemania',
    repo: 'WWE-Wrestlemania',
    url: 'https://github.com/dglogan42/WWE-Wrestlemania',
    emoji: '💪',
    tagline: 'Road to WrestleMania hype cards. Roast superstars IWC style.',
    memeTop: 'ROAD TO WRESTLEMANIA',
    memeBottom: 'hype your guy. roast the fed.',
    bg: 'stream',
  },
  {
    id: 'pga-masters',
    name: 'PGA-Masters',
    repo: 'PGA-Masters',
    url: 'https://github.com/dglogan42/PGA-Masters',
    emoji: '⛳',
    tagline: 'PGA Tour leaderboards, FedEx Cup, Masters Fan Zone.',
    memeTop: 'BIRDIE FEED ACTIVATED',
    memeBottom: 'masters fan zone clip studio',
    bg: 'pandemic',
  },
  {
    id: 'asian-supermarket',
    name: 'Asian-Supermarket',
    repo: 'Asian-Supermarket',
    url: 'https://github.com/dglogan42/Asian-Supermarket',
    emoji: '🛒',
    tagline: 'Find Asian supermarkets. Voice search. Hungry Panda delivery.',
    memeTop: 'ASIAN SUPERMARKET LOCATOR',
    memeBottom: 'hungry panda integration nobody asked for',
    bg: 'berry',
  },
  {
    id: 'healthpoint',
    name: 'Healthpoint',
    repo: 'Healthpoint',
    url: 'https://github.com/dglogan42/Healthpoint',
    emoji: '🏥',
    tagline: 'NZ chemists, GPs, physios, ACC/WINZ — maps linked.',
    memeTop: 'HEALTHPOINT FINDER',
    memeBottom: 'find a chemist in aotearoa bestie',
    bg: 'ai',
  },
  {
    id: 'anime-filter',
    name: 'Instagram-Anime-Effect',
    repo: 'Instagram-Anime-Effect',
    url: 'https://github.com/dglogan42/Instagram-Anime-Effect',
    emoji: '🎨',
    tagline: 'Cel-shaded anime camera filter PWA for Instagram.',
    memeTop: 'ANIME FILTER PWA',
    memeBottom: 'instagram stories but youre ghibli',
    bg: 'adhd',
  },
  {
    id: 'european-pantry',
    name: 'European-Pantry',
    repo: 'European-Pantry',
    url: 'https://github.com/dglogan42/European-Pantry',
    emoji: '🥐',
    tagline: 'European food shop for NZ — Auckland, Wellington, Christchurch.',
    memeTop: 'CONTINENTAL PANTRY',
    memeBottom: 'european snacks in christchurch',
    bg: 'liveLaugh',
  },
  {
    id: 'ozbiz',
    name: 'OzBiz-Properties',
    repo: 'OzBiz-Properties',
    url: 'https://github.com/dglogan42/OzBiz-Properties',
    emoji: '🏢',
    tagline: 'Australian commercial real estate — offices, warehouses, retail.',
    memeTop: 'OZBIZ PROPERTIES',
    memeBottom: 'warehouse industrial core australia',
    bg: 'ai',
  },
  {
    id: 'rednote-trader',
    name: 'Rednote-Trader',
    repo: 'Rednote-Trader',
    url: 'https://github.com/dglogan42/Rednote-Trader',
    emoji: '📕',
    tagline: 'Xiaohongshu-style marketplace with Stripe & PayPal.',
    memeTop: 'REDNOTE TRADING',
    memeBottom: 'little red book but make it stripe',
    bg: 'berry',
  },
  {
    id: 'rednote-streaming',
    name: 'Rednote-Streaming',
    repo: 'Rednote-Streaming',
    url: 'https://github.com/dglogan42/Rednote-Streaming',
    emoji: '📺',
    tagline: 'RedNote Chrome extension — livestream to X and Bluesky.',
    memeTop: 'REDNOTE EXTENSION',
    memeBottom: 'livestream xiaohongshu to bluesky',
    bg: 'stream',
  },
  {
    id: 'uncensored-ai',
    name: 'Uncensored-AI',
    repo: 'Uncensored-AI',
    url: 'https://github.com/dglogan42/Uncensored-AI',
    emoji: '🤖',
    tagline: 'Local AI studio — SD, LLMs, Whisper, Kokoro, video gen.',
    memeTop: 'UNCENSORED LOCAL STUDIO',
    memeBottom: 'stable diffusion on my laptop at 3am',
    bg: 'ai',
  },
  {
    id: 'cringe-memes',
    name: 'cringe-memes-bluesky',
    repo: 'cringe-memes-bluesky',
    url: 'https://github.com/dglogan42/cringe-memes-bluesky',
    emoji: '🦋',
    tagline: 'This app. Bluesky feed → cringe memes. Maximum regret.',
    memeTop: 'CRINGE MEME GENERATOR',
    memeBottom: 'recursively cringe (this repo)',
    bg: 'berry',
  },
];

export const PROJECT_CATEGORIES = [
  { id: 'all', label: 'All Chaos' },
  { id: 'sports', label: '🏆 Sports' },
  { id: 'chaos', label: '💀 Chaos Apps' },
  { id: 'commerce', label: '🛒 Commerce' },
];

export const PROJECT_CATEGORY_MAP = {
  'abg-finder': 'chaos',
  'valorant-streamer': 'chaos',
  'glasgow-2026': 'sports',
  'sports-clip-studio': 'sports',
  'f1-season': 'sports',
  'le-tour': 'sports',
  '12th-man': 'sports',
  'all-blacks': 'sports',
  'wimbledon': 'sports',
  'wwe': 'sports',
  'pga-masters': 'sports',
  'asian-supermarket': 'commerce',
  'healthpoint': 'chaos',
  'anime-filter': 'chaos',
  'european-pantry': 'commerce',
  'ozbiz': 'commerce',
  'rednote-trader': 'commerce',
  'rednote-streaming': 'chaos',
  'uncensored-ai': 'chaos',
  'cringe-memes': 'chaos',
};