import {
  THE_DOCTOR_JPG_PROJECTS,
  THE_DOCTOR_JPG_CATEGORIES,
  THE_DOCTOR_JPG_CATEGORY_MAP,
} from './projects-thedoctorjpg.js';

/** @dglogan42's stupid GitHub portfolio — meme fuel */
export const DGLOGAN42_PROJECTS = [
  {
    id: 'abg-finder',
    owner: 'dglogan42',
    name: 'ABG-Finder',
    repo: 'ABG-Finder',
    url: 'https://github.com/dglogan42/ABG-Finder',
    emoji: '💅',
    tagline: 'Swipe ABGs, rate bubble tea sweetness, track the sauce.',
    memeTop: 'ME BUILDING AN ABG DATING APP',
    memeBottom: 'with ramen spiciness ratings fr',
    bg: 'berry',
  },
  {
    id: 'valorant-streamer',
    owner: 'dglogan42',
    name: 'Valorant-Streamer',
    repo: 'Valorant-Streamer',
    url: 'https://github.com/dglogan42/Valorant-Streamer',
    emoji: '▲',
    tagline: 'Twitch ladder, gift subs, Throne wishlists, clip studio.',
    memeTop: 'STREAMLADDER MMR',
    memeBottom: 'clip the ace. post the cringe gif.',
    bg: 'stream',
  },
  {
    id: 'glasgow-2026',
    owner: 'dglogan42',
    name: 'Glasgow-2026',
    repo: 'Glasgow-2026',
    url: 'https://github.com/dglogan42/Glasgow-2026',
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    tagline: 'Morag MacMeme Scots TTS for Commonwealth Games chaos.',
    memeTop: 'MORAG MACMEME SAID',
    memeBottom: 'pure gallus commonwealth energy',
    bg: 'liveLaugh',
  },
  {
    id: 'sports-clip-studio',
    owner: 'dglogan42',
    name: 'sports-clip-studio',
    repo: 'sports-clip-studio',
    url: 'https://github.com/dglogan42/sports-clip-studio',
    emoji: '✂️',
    tagline: 'Trim sports commentary clips. Share to Bluesky & podcasts.',
    memeTop: 'SPORTS CLIP STUDIO',
    memeBottom: 'trim the hype. blast it to mastodon.',
    bg: 'fifa',
  },
  {
    id: 'f1-season',
    owner: 'dglogan42',
    name: 'F1-Season',
    repo: 'F1-Season',
    url: 'https://github.com/dglogan42/F1-Season',
    emoji: '🏎️',
    tagline: '2026 championship dashboard, Monaco timeline, Speed Racer memes.',
    memeTop: 'ROAD TO MONACO',
    memeBottom: 'radiohead lyrics but make it f1',
    bg: 'fifa',
  },
  {
    id: 'le-tour',
    owner: 'dglogan42',
    name: 'le-tour',
    repo: 'le-tour',
    url: 'https://github.com/dglogan42/le-tour',
    emoji: '🚴',
    tagline: 'Tour de France tracker with unreasonable French meme energy.',
    memeTop: 'MAILLot JAUNE ENERGY',
    memeBottom: 'openstreetmap but make it baguette',
    bg: 'liveLaugh',
  },
  {
    id: '12th-man',
    owner: 'dglogan42',
    name: '12th-Man',
    repo: '12th-Man',
    url: 'https://github.com/dglogan42/12th-Man',
    emoji: '🏏',
    tagline: 'Twelfth Man spoof Ashes commentary with Bill Lawry chaos.',
    memeTop: 'BILL LAWRY AT 3AM',
    memeBottom: 'marvellous marvellous ashes tts',
    bg: 'fifa',
  },
  {
    id: 'all-blacks',
    owner: 'dglogan42',
    name: 'All-Blacks-Season',
    repo: 'All-Blacks-Season',
    url: 'https://github.com/dglogan42/All-Blacks-Season',
    emoji: '🏉',
    tagline: 'Bledisloe Cup tracker + sausage roll stadium reviews.',
    memeTop: 'ALL BLACKS SEASON',
    memeBottom: 'election week crowd spotting nz',
    bg: 'pandemic',
  },
  {
    id: 'wimbledon',
    owner: 'dglogan42',
    name: 'Road-To-Wimbledon',
    repo: 'Road-To-Wimbledon',
    url: 'https://github.com/dglogan42/Road-To-Wimbledon',
    emoji: '🎾',
    tagline: 'ASB Classic → Roland Garros → Wimbledon drama meters.',
    memeTop: 'TANTRUM TICKER SAYS',
    memeBottom: 'celebrity spotter at all england',
    bg: 'liveLaugh',
  },
  {
    id: 'wwe',
    owner: 'dglogan42',
    name: 'WWE-Wrestlemania',
    repo: 'WWE-Wrestlemania',
    url: 'https://github.com/dglogan42/WWE-Wrestlemania',
    emoji: '💪',
    tagline: 'Road to WrestleMania hype cards. Roast superstars IWC style.',
    memeTop: 'ROAD TO WRESTLEMANIA',
    memeBottom: 'hype your guy. roast the fed.',
    bg: 'stream',
  },
  {
    id: 'pga-masters',
    owner: 'dglogan42',
    name: 'PGA-Masters',
    repo: 'PGA-Masters',
    url: 'https://github.com/dglogan42/PGA-Masters',
    emoji: '⛳',
    tagline: 'PGA Tour leaderboards, FedEx Cup, Masters Fan Zone.',
    memeTop: 'BIRDIE FEED ACTIVATED',
    memeBottom: 'masters fan zone clip studio',
    bg: 'pandemic',
  },
  {
    id: 'asian-supermarket',
    owner: 'dglogan42',
    name: 'Asian-Supermarket',
    repo: 'Asian-Supermarket',
    url: 'https://github.com/dglogan42/Asian-Supermarket',
    emoji: '🛒',
    tagline: 'Find Asian supermarkets. Voice search. Hungry Panda delivery.',
    memeTop: 'ASIAN SUPERMARKET LOCATOR',
    memeBottom: 'hungry panda integration nobody asked for',
    bg: 'berry',
  },
  {
    id: 'healthpoint',
    owner: 'dglogan42',
    name: 'Healthpoint',
    repo: 'Healthpoint',
    url: 'https://github.com/dglogan42/Healthpoint',
    emoji: '🏥',
    tagline: 'NZ chemists, GPs, physios, ACC/WINZ — maps linked.',
    memeTop: 'HEALTHPOINT FINDER',
    memeBottom: 'find a chemist in aotearoa bestie',
    bg: 'ai',
  },
  {
    id: 'anime-filter',
    owner: 'dglogan42',
    name: 'Instagram-Anime-Effect',
    repo: 'Instagram-Anime-Effect',
    url: 'https://github.com/dglogan42/Instagram-Anime-Effect',
    emoji: '🎨',
    tagline: 'Cel-shaded anime camera filter PWA for Instagram.',
    memeTop: 'ANIME FILTER PWA',
    memeBottom: 'instagram stories but youre ghibli',
    bg: 'adhd',
  },
  {
    id: 'european-pantry',
    owner: 'dglogan42',
    name: 'European-Pantry',
    repo: 'European-Pantry',
    url: 'https://github.com/dglogan42/European-Pantry',
    emoji: '🥐',
    tagline: 'European food shop for NZ — Auckland, Wellington, Christchurch.',
    memeTop: 'CONTINENTAL PANTRY',
    memeBottom: 'european snacks in christchurch',
    bg: 'liveLaugh',
  },
  {
    id: 'ozbiz',
    owner: 'dglogan42',
    name: 'OzBiz-Properties',
    repo: 'OzBiz-Properties',
    url: 'https://github.com/dglogan42/OzBiz-Properties',
    emoji: '🏢',
    tagline: 'Australian commercial real estate — offices, warehouses, retail.',
    memeTop: 'OZBIZ PROPERTIES',
    memeBottom: 'warehouse industrial core australia',
    bg: 'ai',
  },
  {
    id: 'rednote-trader',
    owner: 'dglogan42',
    name: 'Rednote-Trader',
    repo: 'Rednote-Trader',
    url: 'https://github.com/dglogan42/Rednote-Trader',
    emoji: '📕',
    tagline: 'Xiaohongshu-style marketplace with Stripe & PayPal.',
    memeTop: 'REDNOTE TRADING',
    memeBottom: 'little red book but make it stripe',
    bg: 'berry',
  },
  {
    id: 'rednote-streaming',
    owner: 'dglogan42',
    name: 'Rednote-Streaming',
    repo: 'Rednote-Streaming',
    url: 'https://github.com/dglogan42/Rednote-Streaming',
    emoji: '📺',
    tagline: 'RedNote Chrome extension — livestream to X and Bluesky.',
    memeTop: 'REDNOTE EXTENSION',
    memeBottom: 'livestream xiaohongshu to bluesky',
    bg: 'stream',
  },
  {
    id: 'uncensored-ai',
    owner: 'dglogan42',
    name: 'Uncensored-AI',
    repo: 'Uncensored-AI',
    url: 'https://github.com/dglogan42/Uncensored-AI',
    emoji: '🤖',
    tagline: 'Local AI studio — SD, LLMs, Whisper, Kokoro, video gen.',
    memeTop: 'UNCENSORED LOCAL STUDIO',
    memeBottom: 'stable diffusion on my laptop at 3am',
    bg: 'ai',
  },
  {
    id: 'creampie-calculator',
    owner: 'dglogan42',
    name: 'Creampie-Time-Calculator',
    repo: 'Creampie-Time-Calculator',
    url: 'https://github.com/dglogan42/Creampie-Time-Calculator',
    emoji: '🥧',
    tagline: 'Ovulation tracker with whipped-cream pastry alert when it\'s baby time.',
    memeTop: 'CREAMPIE TIME CALCULATOR',
    memeBottom: 'load the whipped cream at ovulation o\'clock',
    bg: 'berry',
  },
  {
    id: 'hogwarts-sherlock',
    owner: 'dglogan42',
    name: 'Hogwarts-Sherlock',
    repo: 'Hogwarts-Sherlock',
    url: 'https://github.com/dglogan42/Hogwarts-Sherlock',
    emoji: '🔍',
    tagline: '33k-word EPUB — Mr Holmes on TikTok meets teenage secret notebook energy.',
    memeTop: 'ELEMENTARY MY DEAR TIKTOKER',
    memeBottom: 'chromatography at baker street secondary fr',
    bg: 'adhd',
  },
  {
    id: 'openstream',
    owner: 'dglogan42',
    name: 'Openstream',
    repo: 'Openstream',
    url: 'https://github.com/dglogan42/Openstream',
    emoji: '📡',
    tagline: 'Free open-source multi-site streamer — one ingest, many platforms via FFmpeg.',
    memeTop: 'STREAM ONCE TO EVERYTHING',
    memeBottom: 'self-hosted restream on a free plan forever',
    bg: 'stream',
  },
  {
    id: 'openrestream',
    owner: 'dglogan42',
    name: 'Openrestream',
    repo: 'Openrestream',
    url: 'https://github.com/dglogan42/Openrestream',
    emoji: '🔀',
    tagline: 'Sister restream chaos — open multi-destination broadcast experiments.',
    memeTop: 'OPENRESTREAM PROTOCOL',
    memeBottom: 'because one stream platform is never enough',
    bg: 'stream',
  },
  {
    id: 'beastwars-tcg',
    owner: 'dglogan42',
    name: 'Beastwars-TCG',
    repo: 'Beastwars-TCG',
    url: 'https://github.com/dglogan42/Beastwars-TCG',
    emoji: '🤖',
    tagline: 'Beast Wars Transformers TCG PWA — 100+ cards, expansions, battle vs AI.',
    memeTop: 'BEAST WARS TCG LIVE',
    memeBottom: 'energon cost 5. waszinator gets ko\'d again',
    bg: 'fifa',
  },
  {
    id: 'christmas-countdown',
    owner: 'dglogan42',
    name: 'Christmas-Countdown',
    repo: 'Christmas-Countdown',
    url: 'https://github.com/dglogan42/Christmas-Countdown',
    emoji: '🎄',
    tagline: 'Buddy, Grinch & Jack — cozy -ber months, raid party, Feliz Navidad karaoke PWA.',
    memeTop: 'COUNTDOWN TO CHRISTMAS',
    memeBottom: 'jack singing feliz navidad at the halloween raid',
    bg: 'liveLaugh',
  },
  {
    id: 'azogue-netflix',
    owner: 'dglogan42',
    name: 'Azogue-Netflix',
    repo: 'Azogue-Netflix',
    url: 'https://github.com/dglogan42/Azogue-Netflix',
    emoji: '🎬',
    tagline: 'Netflix-adjacent viewing chaos. Queue the doomscroll.',
    memeTop: 'AZOGUE NETFLIX',
    memeBottom: 'are you still watching? of course you are',
    bg: 'stream',
  },
  {
    id: 'slam-poet',
    owner: 'dglogan42',
    name: 'Slam-Poet',
    repo: 'Slam-Poet',
    url: 'https://github.com/dglogan42/Slam-Poet',
    emoji: '🎤',
    tagline: 'Spoken-word / slam poetry tooling for the mic-drop adjacent.',
    memeTop: 'SLAM POET MODE',
    memeBottom: 'finger snaps in the comments only',
    bg: 'adhd',
  },
  {
    id: 'the-fallen-seed',
    owner: 'dglogan42',
    name: 'THE-FALLEN-SEED',
    repo: 'THE-FALLEN-SEED',
    url: 'https://github.com/dglogan42/THE-FALLEN-SEED',
    emoji: '🌱',
    tagline: 'Dark-seed creative project energy. Grow something cursed.',
    memeTop: 'THE FALLEN SEED',
    memeBottom: 'plant trauma. harvest lore.',
    bg: 'pandemic',
  },
  {
    id: 'adhd-ardour',
    owner: 'dglogan42',
    name: 'ADHD-Ardour',
    repo: 'ADHD-Ardour',
    url: 'https://github.com/dglogan42/ADHD-Ardour',
    emoji: '🎛️',
    tagline: 'Ardour DAW + ADHD workflow chaos. Record before the hyperfocus ends.',
    memeTop: 'ADHD ARDOUR SESSION',
    memeBottom: '17 tracks muted. one perfect take. lost the project file.',
    bg: 'adhd',
  },
  {
    id: 'observability-toolkit',
    owner: 'dglogan42',
    name: 'observability-monitoring-toolkit',
    repo: 'observability-monitoring-toolkit',
    url: 'https://github.com/dglogan42/observability-monitoring-toolkit',
    emoji: '📊',
    tagline: 'Monitoring / observability toolkit. Graphs for people who graph their feelings.',
    memeTop: 'OBSERVABILITY TOOLKIT',
    memeBottom: 'my metrics are down bad',
    bg: 'ai',
  },
  {
    id: 'cringe-memes',
    owner: 'dglogan42',
    name: 'cringe-memes-bluesky',
    repo: 'cringe-memes-bluesky',
    url: 'https://github.com/dglogan42/cringe-memes-bluesky',
    emoji: '🦋',
    tagline: 'This app. Bluesky feed → cringe memes. Maximum regret.',
    memeTop: 'CRINGE MEME GENERATOR',
    memeBottom: 'recursively cringe (this repo)',
    bg: 'berry',
  },
];

export const PROJECT_CATEGORIES = [
  { id: 'all', label: 'All Chaos' },
  { id: 'sports', label: '🏆 Sports' },
  { id: 'games', label: '🎮 Games' },
  { id: 'chaos', label: '💀 Chaos Apps' },
  { id: 'commerce', label: '🛒 Commerce' },
  { id: 'writing', label: '✍️ Writing' },
];

export const PROJECT_CATEGORY_MAP = {
  'abg-finder': 'chaos',
  'valorant-streamer': 'chaos',
  'glasgow-2026': 'sports',
  'sports-clip-studio': 'sports',
  'f1-season': 'sports',
  'le-tour': 'sports',
  '12th-man': 'sports',
  'all-blacks': 'sports',
  'wimbledon': 'sports',
  'wwe': 'sports',
  'pga-masters': 'sports',
  'asian-supermarket': 'commerce',
  'healthpoint': 'chaos',
  'anime-filter': 'chaos',
  'european-pantry': 'commerce',
  'ozbiz': 'commerce',
  'rednote-trader': 'commerce',
  'rednote-streaming': 'chaos',
  'uncensored-ai': 'chaos',
  'creampie-calculator': 'chaos',
  'hogwarts-sherlock': 'writing',
  'openstream': 'chaos',
  'openrestream': 'chaos',
  'beastwars-tcg': 'games',
  'christmas-countdown': 'chaos',
  'azogue-netflix': 'chaos',
  'slam-poet': 'writing',
  'the-fallen-seed': 'writing',
  'adhd-ardour': 'chaos',
  'observability-toolkit': 'chaos',
  'cringe-memes': 'chaos',
};

/** @deprecated use DGLOGAN42_PROJECTS */
export const GITHUB_PROJECTS = DGLOGAN42_PROJECTS;

export const GITHUB_ACCOUNTS = [
  {
    id: 'dglogan42',
    username: 'dglogan42',
    label: '@dglogan42',
    url: 'https://github.com/dglogan42',
    projects: DGLOGAN42_PROJECTS,
    categories: PROJECT_CATEGORIES,
    categoryMap: PROJECT_CATEGORY_MAP,
  },
  {
    id: 'thedoctorjpg',
    username: 'Thedoctorjpg',
    label: '@Thedoctorjpg',
    url: 'https://github.com/Thedoctorjpg',
    projects: THE_DOCTOR_JPG_PROJECTS,
    categories: THE_DOCTOR_JPG_CATEGORIES,
    categoryMap: THE_DOCTOR_JPG_CATEGORY_MAP,
  },
];